**2017**

       Google introduced Transformer architecture
       paper : Attention all you need
       Machine translation : One language to another language
       Replace by : RNNS
       No one use RNNS

**2018:**

      Google developed BERT
      So many NLP model developed using this concept
      QA, Classification,Summary,NER
      BERT : RoBERTa, ALBERT, DistiliBERT (model)

**2019:**

     Huggingface Launches transformers library
     load a pretrained models :  2M models are there now

**2020:**

    GPT3  OpenAI introduces GPT3
    LLM concept evolved

**2021-2023**

          Google : T5
          Meta : llama
          Hugginggace : support all models

**2023:**

          ChatGPT era
          Huggingface : support
          so many models  ==== AI is established

| **Task**                           | **Common Transformers Classes**                                                                            | **Description**                                                  |
| ---------------------------------- | ---------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- |
| **Sentiment analysis**             | `BertForSequenceClassification`, `DistilBertForSequenceClassification`, `RobertaForSequenceClassification` | Classifies text as positive/negative or multi-class sentiment.   |
| **Text generation (English)**      | `GPT2LMHeadModel`, `AutoModelForCausalLM`                                                                  | Generates text given a prompt (causal language modeling).        |
| **Named entity recognition (NER)** | `BertForTokenClassification`, `RobertaForTokenClassification`                                              | Labels each token with an entity type (person, location, etc.).  |
| **Question answering**             | `BertForQuestionAnswering`, `RobertaForQuestionAnswering`, `DistilBertForQuestionAnswering`                | Extracts answer spans from a given context.                      |
| **Filling masked text**            | `BertForMaskedLM`, `RobertaForMaskedLM`                                                                    | Predicts masked tokens in a sentence (masked language modeling). |
| **Summarization**                  | `BartForConditionalGeneration`, `T5ForConditionalGeneration`                                               | Generates a summary from long text.                              |
| **Translation**                    | `MarianMTModel`, `T5ForConditionalGeneration`, `MBartForConditionalGeneration`                             | Translates text between languages.                               |
| **Feature extraction**             | `BertModel`, `RobertaModel`, `DistilBertModel`                                                             | Returns hidden states/tensor embeddings of text.                 |

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)

## Use case

- Understanding the model

- Here we are not doing any task

- Here we read the model

- We understand about tokenizer,vocabulary and embeddings

In [ ]:
from transformers import BertModel, BertTokenizer
# Every model has its own tokenizer
# Its own words dictinary , it is called vocabulary
# we need to create the Embeddings using tokenizer and vocab
# in order to load the model : BertModel
# in order to load the tokenizer: BertTokenizer

- Every model will have

    - Tokenizer

    - Vocabulary

- Vocabulary is words list nothing but a Dictionary

- Tokenizer is used to token the sentence

- Which means divide the sentence into words also called as tokens

- those tokens or words should be available in **vocabulary**

- BertModel is used to access the Models

- BertTokenizer is used to get the model vocabulary

access the model

model name is : **bert-base-uncased**

- **bert base** :

 - 110M parameters

 - 12 layers

 - 768 Neurons

- **bert large** :

 - 340M Parameters

 - 24 layers

 - 1024 Neurons

In [ ]:
model=BertModel.from_pretrained('bert-base-uncased')
# model name is = 'bert-base-uncased'

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
# from transformers import pipeline
# unmasker = pipeline('fill-mask', model='bert-base-uncased')
# unmasker("Hello I'm a [MASK] model.")

In [ ]:
dir(model)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adjust_missing_and_unexpected_keys',
 '_apply',
 '_auto_class',
 '_backward_compatibility_gradient_checkpointing',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_can_compile_fullgraph',
 '_can_record_outputs',
 '_can_set_attn_implementation',
 '_check_and_adjust_attn_implementation',
 '_checkpoint_conversion_mapping',
 '_compiled_call_impl',
 '_convert_head_mask_to_5d',
 '_copy_lm_head_original_to_resized',
 '_create_repo',
 '_dispatch_accelerate_model',
 '_ep_plan',
 '_fix_state_dict_key_on_load',
 '_fix_state_dict_key_on_save',
 '_fix_state_dict_keys_on_save',
 '_flash_attn_2_can_dispatch',
 '_flash_attn_3_can_dispatch',
 '_flex_attn_can_dispatch',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_from_config',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_files_timestamps',
 '_get_key_renaming_mapping',
 '_get_name',
 '_get_no_split_modules',
 '_get_resized_embeddings',
 '_get_resized_lm_head',
 '_hf_peft_config_loaded',
 '_hook_rss_memory_post_forward',
 '_hook_rss_memory_pre_forward',
 '_init_added_embeddings_weights_with_mean',
 '_init_added_lm_head_bias_with_mean',
 '_init_added_lm_head_weights_with_mean',
 '_init_weights',
 '_initialize_missing_keys',
 '_initialize_weights',
 '_input_embed_layer',
 '_is_full_backward_hook',
 '_is_hf_initialized',
 '_is_stateful',
 '_keep_in_fp32_modules',
 '_keep_in_fp32_modules',
 '_keep_in_fp32_modules_strict',
 '_keep_in_fp32_modules_strict',
 '_keys_to_ignore_on_load_missing',
 '_keys_to_ignore_on_load_unexpected',
 '_keys_to_ignore_on_save',
 '_load_from_flax',
 '_load_from_state_dict',
 '_load_from_tf',
 '_load_pretrained_model',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_move_missing_keys_from_meta_to_cpu',
 '_named_members',
 '_no_split_modules',
 '_no_split_modules',
 '_non_persistent_buffers_set',
 '_parameters',
 '_pp_plan',
 '_pp_plan',
 '_prune_heads',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_resize_token_embeddings',
 '_save_to_state_dict',
 '_sdpa_can_dispatch',
 '_set_default_dtype',
 '_set_gradient_checkpointing',
 '_skip_keys_device_placement',
 '_slow_forward',
 '_state_dict_hooks',
 '_state_dict_pre_hooks',
 '_supports_attention_backend',
 '_supports_flash_attn',
 '_supports_flex_attn',
 '_supports_sdpa',
 '_tie_encoder_decoder_weights',
 '_tie_or_clone_weights',
 '_tied_weights_keys',
 '_tp_plan',
 '_tp_plan',
 '_tp_size',
 '_upload_modified_files',
 '_version',
 '_wrapped_call_impl',
 'active_adapters',
 'add_adapter',
 'add_memory_hooks',
 'add_model_tags',
 'add_module',
 'apply',
 'attn_implementation',
 'base_model',
 'base_model_prefix',
 'bfloat16',
 'buffers',
 'call_super_init',
 'can_generate',
 'can_record_outputs',
 'children',
 'compile',
 'config',
 'config_class',
 'cpu',
 'create_extended_attention_mask_for_decoder',
 'cuda',
 'delete_adapter',
 'dequantize',
 'device',
 'disable_adapters',
 'disable_input_require_grads',
 'double',
 'dtype',
 'dummy_inputs',
 'dump_patches',
 'embeddings',
 'enable_adapters',
 'enable_input_require_grads',
 'encoder',
 'estimate_tokens',
 'eval',
 'extra_repr',
 'float',
 'floating_point_ops',
 'forward',
 'framework',
 'from_pretrained',
 'generation_config',
 'get_adapter_state_dict',
 'get_buffer',
 'get_compiled_call',
 'get_correct_attn_implementation',
 'get_decoder',
 'get_extended_attention_mask',
 'get_extra_state',
 'get_head_mask',
 'get_init_context',
 'get_input_embeddings',
 'get_memory_footprint',
 'get_output_embeddings',
 'get_parameter',
 'get_parameter_or_buffer',
 'get_position_embeddings',
 'get_submodule',
 'gradient_checkpointing_disable',
 'gradient_checkpointing_enable',
 'half',
 'init_weights',
 'initialize_weights',
 'invert_attention_mask',
 'ipu',
 'is_backend_compatible',
 'is_gradient_checkpointing',
 'is_parallelizable',
 'kernelize',
 'load_adapter',
 'load_state_dict',
 'load_tf_weights',
 'loss_function',
 'loss_type',
 'main_input_name',
 'model_tags',
 'modules',
 'mtia',
 'name_or_path',
 'named_buffers',
 'named_children',
 'named_modules',
 'named_parameters',
 'num_parameters',
 'parameters',
 'pooler',
 'position_embedding_type',
 'post_init',
 'pp_plan',
 'prune_heads',
 'push_to_hub',
 'register_backward_hook',
 'register_buffer',
 'register_for_auto_class',
 'register_forward_hook',
 'register_forward_pre_hook',
 'register_full_backward_hook',
 'register_full_backward_pre_hook',
 'register_load_state_dict_post_hook',
 'register_load_state_dict_pre_hook',
 'register_module',
 'register_parameter',
 'register_state_dict_post_hook',
 'register_state_dict_pre_hook',
 'requires_grad_',
 'reset_memory_hooks_state',
 'resize_position_embeddings',
 'resize_token_embeddings',
 'retrieve_modules_from_names',
 'reverse_bettertransformer',
 'save_pretrained',
 'set_adapter',
 'set_attn_implementation',
 'set_decoder',
 'set_extra_state',
 'set_input_embeddings',
 'set_output_embeddings',
 'set_submodule',
 'share_memory',
 'smart_apply',
 'state_dict',
 'supports_gradient_checkpointing',
 'supports_pp_plan',
 'supports_tp_plan',
 'tie_embeddings_and_encoder_decoder',
 'tie_weights',
 'to',
 'to_bettertransformer',
 'to_empty',
 'tp_plan',
 'tp_size',
 'train',
 'training',
 'type',
 'use_kernels',
 'warn_if_padding_and_no_attention_mask',
 'warnings_issued',
 'xpu',
 'zero_grad']

In [ ]:
model.framework
model.name_or_path
model.num_parameters()
model.base_model  # Embeddings Encoder pooler
model.embeddings
model.Encoder
model.pooler

AttributeError: 'BertModel' object has no attribute 'Encoder'

In [ ]:
model.framework

# pt = pytorch framework
# DL NLP
# tf pt

- By defualt Hugging face transformers based on pytorch

- if we want to use tensorflow then class will be change

In [ ]:
# from transformers import TFBertModel, BertTokenizer
# tfmodel=TFBertModel.from_pretrained('bert-base-uncased')
# tfmodel.framework  # Deprecated

In [ ]:
model.generation_config  # No output

In [ ]:
model.name_or_path

In [ ]:
model.num_parameters()  # 110M

In [ ]:
model.base_model
# 30522= vocabulary list  there are 30522 tokens
# 768= vector size , each token vector length is 768
# each token represnt as 768 size of vector

# position_embeddings: 512 : any sentence will truncate to 512 tokens only
# the maximum tokens are only 512

# token_type_embeddings : sentence pair
# at a time it can make it as only two sentences

- It will take each and every word

- It will give the word embeddings of each word

- Assume that a sentence has 100 words

- will get 100 word embeddings each vector has 768 values

- 100 words means   (100,768)

- Will apply one pool layer : similar analogy average of all vectors === activation function

- Again the final sentence word embeddings is a size of 768

In [ ]:
# directory embedding
model.embeddings

In [ ]:
model.encoder

In [ ]:
# for i in model.named_parameters():
#     print(i)

In [ ]:
#for i in model.naparameters():
    #print(i)

In [ ]:
#for i in model.named_parameters():
    #print(i)

# coding round  sql
# ML : Resume
# Manger round

## Bert Tokenizer

In [ ]:
sentence='we are learning bert embeddings'

In [ ]:
tokenizer=BertTokenizer.from_pretrained('bert-base-uncased')
tokenizer

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

BertTokenizer(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

- SEP token is used to seperate the sentences

    - Hello how are you. Im learning BERT

    - Hello how are you [SEP] Im learning BERT

- CLS token is used to close the the sentence , also called as Classification token, It is used at starting for classification task

    - [CLS] Hello how are you [SEP] Im learning BERT [SEP]

    - [CLS] token specificall used to classifiation problem

        - sentiment analysis

        - Q and A

        - intent classification etc

    - [CLS] will pass through all BERT layers

    - final layer will pass through pooling layer on top of that will apply tanh

    - only one vector that to [cls] token vector

    - this [cls] token represents whole sentence information

- UNK token indicates that token not present in the vocabualry

- Max length of tokens is 512

- In each sentence the model takes 512 words

- Hello how are you. Im learning BERT

    - the number of words :7

    - but we required 512, after 7 will add [PAD] tokens

    - PAD tokens value is zero

**read the vocabulary**

In [ ]:
tokenizer.vocab
# all the words and its index
# the words consider as keys
# total 30522 tokens 0 to 30521
#'[PAD]', '[UNK]', '[CLS]', '[SEP]', '[MASK]'

OrderedDict([('[PAD]', 0),
             ('[unused0]', 1),
             ('[unused1]', 2),
             ('[unused2]', 3),
             ('[unused3]', 4),
             ('[unused4]', 5),
             ('[unused5]', 6),
             ('[unused6]', 7),
             ('[unused7]', 8),
             ('[unused8]', 9),
             ('[unused9]', 10),
             ('[unused10]', 11),
             ('[unused11]', 12),
             ('[unused12]', 13),
             ('[unused13]', 14),
             ('[unused14]', 15),
             ('[unused15]', 16),
             ('[unused16]', 17),
             ('[unused17]', 18),
             ('[unused18]', 19),
             ('[unused19]', 20),
             ('[unused20]', 21),
             ('[unused21]', 22),
             ('[unused22]', 23),
             ('[unused23]', 24),
             ('[unused24]', 25),
             ('[unused25]', 26),
             ('[unused26]', 27),
             ('[unused27]', 28),
             ('[unused28]', 29),
             ('[unused29]', 30),
             ('[unused30]', 31),
             ('[unused31]', 32),
             ('[unused32]', 33),
             ('[unused33]', 34),
             ('[unused34]', 35),
             ('[unused35]', 36),
             ('[unused36]', 37),
             ('[unused37]', 38),
             ('[unused38]', 39),
             ('[unused39]', 40),
             ('[unused40]', 41),
             ('[unused41]', 42),
             ('[unused42]', 43),
             ('[unused43]', 44),
             ('[unused44]', 45),
             ('[unused45]', 46),
             ('[unused46]', 47),
             ('[unused47]', 48),
             ('[unused48]', 49),
             ('[unused49]', 50),
             ('[unused50]', 51),
             ('[unused51]', 52),
             ('[unused52]', 53),
             ('[unused53]', 54),
             ('[unused54]', 55),
             ('[unused55]', 56),
             ('[unused56]', 57),
             ('[unused57]', 58),
             ('[unused58]', 59),
             ('[unused59]', 60),
             ('[unused60]', 61),
             ('[unused61]', 62),
             ('[unused62]', 63),
             ('[unused63]', 64),
             ('[unused64]', 65),
             ('[unused65]', 66),
             ('[unused66]', 67),
             ('[unused67]', 68),
             ('[unused68]', 69),
             ('[unused69]', 70),
             ('[unused70]', 71),
             ('[unused71]', 72),
             ('[unused72]', 73),
             ('[unused73]', 74),
             ('[unused74]', 75),
             ('[unused75]', 76),
             ('[unused76]', 77),
             ('[unused77]', 78),
             ('[unused78]', 79),
             ('[unused79]', 80),
             ('[unused80]', 81),
             ('[unused81]', 82),
             ('[unused82]', 83),
             ('[unused83]', 84),
             ('[unused84]', 85),
             ('[unused85]', 86),
             ('[unused86]', 87),
             ('[unused87]', 88),
             ('[unused88]', 89),
             ('[unused89]', 90),
             ('[unused90]', 91),
             ('[unused91]', 92),
             ('[unused92]', 93),
             ('[unused93]', 94),
             ('[unused94]', 95),
             ('[unused95]', 96),
             ('[unused96]', 97),
             ('[unused97]', 98),
             ('[unused98]', 99),
             ('[UNK]', 100),
             ('[CLS]', 101),
             ('[SEP]', 102),
             ('[MASK]', 103),
             ('[unused99]', 104),
             ('[unused100]', 105),
             ('[unused101]', 106),
             ('[unused102]', 107),
             ('[unused103]', 108),
             ('[unused104]', 109),
             ('[unused105]', 110),
             ('[unused106]', 111),
             ('[unused107]', 112),
             ('[unused108]', 113),
             ('[unused109]', 114),
             ('[unused110]', 115),
             ('[unused111]', 116),
             ('[unused112]', 117),
             ('[unused113]', 118),
             ('[unused114]', 119),
             ('[unused115]', 120),
             ('[unused116]', 121),
             ('[unused117]', 122),
             ('[unused118]', 123),
             ('[unused119]', 124),
             ('[unused120]', 125),
             ('[unused121]', 126),
             ('[unused122]', 127),
             ('[unused123]', 128),
             ('[unused124]', 129),
             ('[unused125]', 130),
             ('[unused126]', 131),
             ('[unused127]', 132),
             ('[unused128]', 133),
             ('[unused129]', 134),
             ('[unused130]', 135),
             ('[unused131]', 136),
             ('[unused132]', 137),
             ('[unused133]', 138),
             ('[unused134]', 139),
             ('[unused135]', 140),
             ('[unused136]', 141),
             ('[unused137]', 142),
             ('[unused138]', 143),
             ('[unused139]', 144),
             ('[unused140]', 145),
             ('[unused141]', 146),
             ('[unused142]', 147),
             ('[unused143]', 148),
             ('[unused144]', 149),
             ('[unused145]', 150),
             ('[unused146]', 151),
             ('[unused147]', 152),
             ('[unused148]', 153),
             ('[unused149]', 154),
             ('[unused150]', 155),
             ('[unused151]', 156),
             ('[unused152]', 157),
             ('[unused153]', 158),
             ('[unused154]', 159),
             ('[unused155]', 160),
             ('[unused156]', 161),
             ('[unused157]', 162),
             ('[unused158]', 163),
             ('[unused159]', 164),
             ('[unused160]', 165),
             ('[unused161]', 166),
             ('[unused162]', 167),
             ('[unused163]', 168),
             ('[unused164]', 169),
             ('[unused165]', 170),
             ('[unused166]', 171),
             ('[unused167]', 172),
             ('[unused168]', 173),
             ('[unused169]', 174),
             ('[unused170]', 175),
             ('[unused171]', 176),
             ('[unused172]', 177),
             ('[unused173]', 178),
             ('[unused174]', 179),
             ('[unused175]', 180),
             ('[unused176]', 181),
             ('[unused177]', 182),
             ('[unused178]', 183),
             ('[unused179]', 184),
             ('[unused180]', 185),
             ('[unused181]', 186),
             ('[unused182]', 187),
             ('[unused183]', 188),
             ('[unused184]', 189),
             ('[unused185]', 190),
             ('[unused186]', 191),
             ('[unused187]', 192),
             ('[unused188]', 193),
             ('[unused189]', 194),
             ('[unused190]', 195),
             ('[unused191]', 196),
             ('[unused192]', 197),
             ('[unused193]', 198),
             ('[unused194]', 199),
             ('[unused195]', 200),
             ('[unused196]', 201),
             ('[unused197]', 202),
             ('[unused198]', 203),
             ('[unused199]', 204),
             ('[unused200]', 205),
             ('[unused201]', 206),
             ('[unused202]', 207),
             ('[unused203]', 208),
             ('[unused204]', 209),
             ('[unused205]', 210),
             ('[unused206]', 211),
             ('[unused207]', 212),
             ('[unused208]', 213),
             ('[unused209]', 214),
             ('[unused210]', 215),
             ('[unused211]', 216),
             ('[unused212]', 217),
             ('[unused213]', 218),
             ('[unused214]', 219),
             ('[unused215]', 220),
             ('[unused216]', 221),
             ('[unused217]', 222),
             ('[unused218]', 223),
             ('[unused219]', 224),
             ('[unused220]', 225),
             ('[unused221]', 226),
             ('[unused222]', 227),
             ('[unused223]', 228),
             ('[unused224]', 229),
             ('[unused225]', 230),
             ('[unused226]', 231),
             ('[unused227]', 232),
             ('[unused228]', 233),
             ('[unused229]', 234),
             ('[unused230]', 235),
             ('[unused231]', 236),
             ('[unused232]', 237),
             ('[unused233]', 238),
             ('[unused234]', 239),
             ('[unused235]', 240),
             ('[unused236]', 241),
             ('[unused237]', 242),
             ('[unused238]', 243),
             ('[unused239]', 244),
             ('[unused240]', 245),
             ('[unused241]', 246),
             ('[unused242]', 247),
             ('[unused243]', 248),
             ('[unused244]', 249),
             ('[unused245]', 250),
             ('[unused246]', 251),
             ('[unused247]', 252),
             ('[unused248]', 253),
             ('[unused249]', 254),
             ('[unused250]', 255),
             ('[unused251]', 256),
             ('[unused252]', 257),
             ('[unused253]', 258),
             ('[unused254]', 259),
             ('[unused255]', 260),
             ('[unused256]', 261),
             ('[unused257]', 262),
             ('[unused258]', 263),
             ('[unused259]', 264),
             ('[unused260]', 265),
             ('[unused261]', 266),
             ('[unused262]', 267),
             ('[unused263]', 268),
             ('[unused264]', 269),
             ('[unused265]', 270),
             ('[unused266]', 271),
             ('[unused267]', 272),
             ('[unused268]', 273),
             ('[unused269]', 274),
             ('[unused270]', 275),
             ('[unused271]', 276),
             ('[unused272]', 277),
             ('[unused273]', 278),
             ('[unused274]', 279),
             ('[unused275]', 280),
             ('[unused276]', 281),
             ('[unused277]', 282),
             ('[unused278]', 283),
             ('[unused279]', 284),
             ('[unused280]', 285),
             ('[unused281]', 286),
             ('[unused282]', 287),
             ('[unused283]', 288),
             ('[unused284]', 289),
             ('[unused285]', 290),
             ('[unused286]', 291),
             ('[unused287]', 292),
             ('[unused288]', 293),
             ('[unused289]', 294),
             ('[unused290]', 295),
             ('[unused291]', 296),
             ('[unused292]', 297),
             ('[unused293]', 298),
             ('[unused294]', 299),
             ('[unused295]', 300),
             ('[unused296]', 301),
             ('[unused297]', 302),
             ('[unused298]', 303),
             ('[unused299]', 304),
             ('[unused300]', 305),
             ('[unused301]', 306),
             ('[unused302]', 307),
             ('[unused303]', 308),
             ('[unused304]', 309),
             ('[unused305]', 310),
             ('[unused306]', 311),
             ('[unused307]', 312),
             ('[unused308]', 313),
             ('[unused309]', 314),
             ('[unused310]', 315),
             ('[unused311]', 316),
             ('[unused312]', 317),
             ('[unused313]', 318),
             ('[unused314]', 319),
             ('[unused315]', 320),
             ('[unused316]', 321),
             ('[unused317]', 322),
             ('[unused318]', 323),
             ('[unused319]', 324),
             ('[unused320]', 325),
             ('[unused321]', 326),
             ('[unused322]', 327),
             ('[unused323]', 328),
             ('[unused324]', 329),
             ('[unused325]', 330),
             ('[unused326]', 331),
             ('[unused327]', 332),
             ('[unused328]', 333),
             ('[unused329]', 334),
             ('[unused330]', 335),
             ('[unused331]', 336),
             ('[unused332]', 337),
             ('[unused333]', 338),
             ('[unused334]', 339),
             ('[unused335]', 340),
             ('[unused336]', 341),
             ('[unused337]', 342),
             ('[unused338]', 343),
             ('[unused339]', 344),
             ('[unused340]', 345),
             ('[unused341]', 346),
             ('[unused342]', 347),
             ('[unused343]', 348),
             ('[unused344]', 349),
             ('[unused345]', 350),
             ('[unused346]', 351),
             ('[unused347]', 352),
             ('[unused348]', 353),
             ('[unused349]', 354),
             ('[unused350]', 355),
             ('[unused351]', 356),
             ('[unused352]', 357),
             ('[unused353]', 358),
             ('[unused354]', 359),
             ('[unused355]', 360),
             ('[unused356]', 361),
             ('[unused357]', 362),
             ('[unused358]', 363),
             ('[unused359]', 364),
             ('[unused360]', 365),
             ('[unused361]', 366),
             ('[unused362]', 367),
             ('[unused363]', 368),
             ('[unused364]', 369),
             ('[unused365]', 370),
             ('[unused366]', 371),
             ('[unused367]', 372),
             ('[unused368]', 373),
             ('[unused369]', 374),
             ('[unused370]', 375),
             ('[unused371]', 376),
             ('[unused372]', 377),
             ('[unused373]', 378),
             ('[unused374]', 379),
             ('[unused375]', 380),
             ('[unused376]', 381),
             ('[unused377]', 382),
             ('[unused378]', 383),
             ('[unused379]', 384),
             ('[unused380]', 385),
             ('[unused381]', 386),
             ('[unused382]', 387),
             ('[unused383]', 388),
             ('[unused384]', 389),
             ('[unused385]', 390),
             ('[unused386]', 391),
             ('[unused387]', 392),
             ('[unused388]', 393),
             ('[unused389]', 394),
             ('[unused390]', 395),
             ('[unused391]', 396),
             ('[unused392]', 397),
             ('[unused393]', 398),
             ('[unused394]', 399),
             ('[unused395]', 400),
             ('[unused396]', 401),
             ('[unused397]', 402),
             ('[unused398]', 403),
             ('[unused399]', 404),
             ('[unused400]', 405),
             ('[unused401]', 406),
             ('[unused402]', 407),
             ('[unused403]', 408),
             ('[unused404]', 409),
             ('[unused405]', 410),
             ('[unused406]', 411),
             ('[unused407]', 412),
             ('[unused408]', 413),
             ('[unused409]', 414),
             ('[unused410]', 415),
             ('[unused411]', 416),
             ('[unused412]', 417),
             ('[unused413]', 418),
             ('[unused414]', 419),
             ('[unused415]', 420),
             ('[unused416]', 421),
             ('[unused417]', 422),
             ('[unused418]', 423),
             ('[unused419]', 424),
             ('[unused420]', 425),
             ('[unused421]', 426),
             ('[unused422]', 427),
             ('[unused423]', 428),
             ('[unused424]', 429),
             ('[unused425]', 430),
             ('[unused426]', 431),
             ('[unused427]', 432),
             ('[unused428]', 433),
             ('[unused429]', 434),
             ('[unused430]', 435),
             ('[unused431]', 436),
             ('[unused432]', 437),
             ('[unused433]', 438),
             ('[unused434]', 439),
             ('[unused435]', 440),
             ('[unused436]', 441),
             ('[unused437]', 442),
             ('[unused438]', 443),
             ('[unused439]', 444),
             ('[unused440]', 445),
             ('[unused441]', 446),
             ('[unused442]', 447),
             ('[unused443]', 448),
             ('[unused444]', 449),
             ('[unused445]', 450),
             ('[unused446]', 451),
             ('[unused447]', 452),
             ('[unused448]', 453),
             ('[unused449]', 454),
             ('[unused450]', 455),
             ('[unused451]', 456),
             ('[unused452]', 457),
             ('[unused453]', 458),
             ('[unused454]', 459),
             ('[unused455]', 460),
             ('[unused456]', 461),
             ('[unused457]', 462),
             ('[unused458]', 463),
             ('[unused459]', 464),
             ('[unused460]', 465),
             ('[unused461]', 466),
             ('[unused462]', 467),
             ('[unused463]', 468),
             ('[unused464]', 469),
             ('[unused465]', 470),
             ('[unused466]', 471),
             ('[unused467]', 472),
             ('[unused468]', 473),
             ('[unused469]', 474),
             ('[unused470]', 475),
             ('[unused471]', 476),
             ('[unused472]', 477),
             ('[unused473]', 478),
             ('[unused474]', 479),
             ('[unused475]', 480),
             ('[unused476]', 481),
             ('[unused477]', 482),
             ('[unused478]', 483),
             ('[unused479]', 484),
             ('[unused480]', 485),
             ('[unused481]', 486),
             ('[unused482]', 487),
             ('[unused483]', 488),
             ('[unused484]', 489),
             ('[unused485]', 490),
             ('[unused486]', 491),
             ('[unused487]', 492),
             ('[unused488]', 493),
             ('[unused489]', 494),
             ('[unused490]', 495),
             ('[unused491]', 496),
             ('[unused492]', 497),
             ('[unused493]', 498),
             ('[unused494]', 499),
             ('[unused495]', 500),
             ('[unused496]', 501),
             ('[unused497]', 502),
             ('[unused498]', 503),
             ('[unused499]', 504),
             ('[unused500]', 505),
             ('[unused501]', 506),
             ('[unused502]', 507),
             ('[unused503]', 508),
             ('[unused504]', 509),
             ('[unused505]', 510),
             ('[unused506]', 511),
             ('[unused507]', 512),
             ('[unused508]', 513),
             ('[unused509]', 514),
             ('[unused510]', 515),
             ('[unused511]', 516),
             ('[unused512]', 517),
             ('[unused513]', 518),
             ('[unused514]', 519),
             ('[unused515]', 520),
             ('[unused516]', 521),
             ('[unused517]', 522),
             ('[unused518]', 523),
             ('[unused519]', 524),
             ('[unused520]', 525),
             ('[unused521]', 526),
             ('[unused522]', 527),
             ('[unused523]', 528),
             ('[unused524]', 529),
             ('[unused525]', 530),
             ('[unused526]', 531),
             ('[unused527]', 532),
             ('[unused528]', 533),
             ('[unused529]', 534),
             ('[unused530]', 535),
             ('[unused531]', 536),
             ('[unused532]', 537),
             ('[unused533]', 538),
             ('[unused534]', 539),
             ('[unused535]', 540),
             ('[unused536]', 541),
             ('[unused537]', 542),
             ('[unused538]', 543),
             ('[unused539]', 544),
             ('[unused540]', 545),
             ('[unused541]', 546),
             ('[unused542]', 547),
             ('[unused543]', 548),
             ('[unused544]', 549),
             ('[unused545]', 550),
             ('[unused546]', 551),
             ('[unused547]', 552),
             ('[unused548]', 553),
             ('[unused549]', 554),
             ('[unused550]', 555),
             ('[unused551]', 556),
             ('[unused552]', 557),
             ('[unused553]', 558),
             ('[unused554]', 559),
             ('[unused555]', 560),
             ('[unused556]', 561),
             ('[unused557]', 562),
             ('[unused558]', 563),
             ('[unused559]', 564),
             ('[unused560]', 565),
             ('[unused561]', 566),
             ('[unused562]', 567),
             ('[unused563]', 568),
             ('[unused564]', 569),
             ('[unused565]', 570),
             ('[unused566]', 571),
             ('[unused567]', 572),
             ('[unused568]', 573),
             ('[unused569]', 574),
             ('[unused570]', 575),
             ('[unused571]', 576),
             ('[unused572]', 577),

In [ ]:
len(tokenizer.vocab)
# understand the type : dictionary type
# keys are tokens only

30522

In [ ]:
tokenizer.vocab.keys()  # only words

# machine
# learning
# machinelearning: machine ##learn ##ing: machine learnig

odict_keys(['[PAD]', '[unused0]', '[unused1]', '[unused2]', '[unused3]', '[unused4]', '[unused5]', '[unused6]', '[unused7]', '[unused8]', '[unused9]', '[unused10]', '[unused11]', '[unused12]', '[unused13]', '[unused14]', '[unused15]', '[unused16]', '[unused17]', '[unused18]', '[unused19]', '[unused20]', '[unused21]', '[unused22]', '[unused23]', '[unused24]', '[unused25]', '[unused26]', '[unused27]', '[unused28]', '[unused29]', '[unused30]', '[unused31]', '[unused32]', '[unused33]', '[unused34]', '[unused35]', '[unused36]', '[unused37]', '[unused38]', '[unused39]', '[unused40]', '[unused41]', '[unused42]', '[unused43]', '[unused44]', '[unused45]', '[unused46]', '[unused47]', '[unused48]', '[unused49]', '[unused50]', '[unused51]', '[unused52]', '[unused53]', '[unused54]', '[unused55]', '[unused56]', '[unused57]', '[unused58]', '[unused59]', '[unused60]', '[unused61]', '[unused62]', '[unused63]', '[unused64]', '[unused65]', '[unused66]', '[unused67]', '[unused68]', '[unused69]', '[unused70]', '[unused71]', '[unused72]', '[unused73]', '[unused74]', '[unused75]', '[unused76]', '[unused77]', '[unused78]', '[unused79]', '[unused80]', '[unused81]', '[unused82]', '[unused83]', '[unused84]', '[unused85]', '[unused86]', '[unused87]', '[unused88]', '[unused89]', '[unused90]', '[unused91]', '[unused92]', '[unused93]', '[unused94]', '[unused95]', '[unused96]', '[unused97]', '[unused98]', '[UNK]', '[CLS]', '[SEP]', '[MASK]', '[unused99]', '[unused100]', '[unused101]', '[unused102]', '[unused103]', '[unused104]', '[unused105]', '[unused106]', '[unused107]', '[unused108]', '[unused109]', '[unused110]', '[unused111]', '[unused112]', '[unused113]', '[unused114]', '[unused115]', '[unused116]', '[unused117]', '[unused118]', '[unused119]', '[unused120]', '[unused121]', '[unused122]', '[unused123]', '[unused124]', '[unused125]', '[unused126]', '[unused127]', '[unused128]', '[unused129]', '[unused130]', '[unused131]', '[unused132]', '[unused133]', '[unused134]', '[unused135]', '[unused136]', '[unused137]', '[unused138]', '[unused139]', '[unused140]', '[unused141]', '[unused142]', '[unused143]', '[unused144]', '[unused145]', '[unused146]', '[unused147]', '[unused148]', '[unused149]', '[unused150]', '[unused151]', '[unused152]', '[unused153]', '[unused154]', '[unused155]', '[unused156]', '[unused157]', '[unused158]', '[unused159]', '[unused160]', '[unused161]', '[unused162]', '[unused163]', '[unused164]', '[unused165]', '[unused166]', '[unused167]', '[unused168]', '[unused169]', '[unused170]', '[unused171]', '[unused172]', '[unused173]', '[unused174]', '[unused175]', '[unused176]', '[unused177]', '[unused178]', '[unused179]', '[unused180]', '[unused181]', '[unused182]', '[unused183]', '[unused184]', '[unused185]', '[unused186]', '[unused187]', '[unused188]', '[unused189]', '[unused190]', '[unused191]', '[unused192]', '[unused193]', '[unused194]', '[unused195]', '[unused196]', '[unused197]', '[unused198]', '[unused199]', '[unused200]', '[unused201]', '[unused202]', '[unused203]', '[unused204]', '[unused205]', '[unused206]', '[unused207]', '[unused208]', '[unused209]', '[unused210]', '[unused211]', '[unused212]', '[unused213]', '[unused214]', '[unused215]', '[unused216]', '[unused217]', '[unused218]', '[unused219]', '[unused220]', '[unused221]', '[unused222]', '[unused223]', '[unused224]', '[unused225]', '[unused226]', '[unused227]', '[unused228]', '[unused229]', '[unused230]', '[unused231]', '[unused232]', '[unused233]', '[unused234]', '[unused235]', '[unused236]', '[unused237]', '[unused238]', '[unused239]', '[unused240]', '[unused241]', '[unused242]', '[unused243]', '[unused244]', '[unused245]', '[unused246]', '[unused247]', '[unused248]', '[unused249]', '[unused250]', '[unused251]', '[unused252]', '[unused253]', '[unused254]', '[unused255]', '[unused256]', '[unused257]', '[unused258]', '[unused259]', '[unused260]', '[unused261]', '[unused262]', '[unused263]', '[unused264]', '[unused265]', '[unused266]', '[unused267]', '[unused268]', '[unused269]', '[unused270]', '[unused271]', '[unused272]', '[unused273]', '[unused274]', '[unused275]', '[unused276]', '[unused277]', '[unused278]', '[unused279]', '[unused280]', '[unused281]', '[unused282]', '[unused283]', '[unused284]', '[unused285]', '[unused286]', '[unused287]', '[unused288]', '[unused289]', '[unused290]', '[unused291]', '[unused292]', '[unused293]', '[unused294]', '[unused295]', '[unused296]', '[unused297]', '[unused298]', '[unused299]', '[unused300]', '[unused301]', '[unused302]', '[unused303]', '[unused304]', '[unused305]', '[unused306]', '[unused307]', '[unused308]', '[unused309]', '[unused310]', '[unused311]', '[unused312]', '[unused313]', '[unused314]', '[unused315]', '[unused316]', '[unused317]', '[unused318]', '[unused319]', '[unused320]', '[unused321]', '[unused322]', '[unused323]', '[unused324]', '[unused325]', '[unused326]', '[unused327]', '[unused328]', '[unused329]', '[unused330]', '[unused331]', '[unused332]', '[unused333]', '[unused334]', '[unused335]', '[unused336]', '[unused337]', '[unused338]', '[unused339]', '[unused340]', '[unused341]', '[unused342]', '[unused343]', '[unused344]', '[unused345]', '[unused346]', '[unused347]', '[unused348]', '[unused349]', '[unused350]', '[unused351]', '[unused352]', '[unused353]', '[unused354]', '[unused355]', '[unused356]', '[unused357]', '[unused358]', '[unused359]', '[unused360]', '[unused361]', '[unused362]', '[unused363]', '[unused364]', '[unused365]', '[unused366]', '[unused367]', '[unused368]', '[unused369]', '[unused370]', '[unused371]', '[unused372]', '[unused373]', '[unused374]', '[unused375]', '[unused376]', '[unused377]', '[unused378]', '[unused379]', '[unused380]', '[unused381]', '[unused382]', '[unused383]', '[unused384]', '[unused385]', '[unused386]', '[unused387]', '[unused388]', '[unused389]', '[unused390]', '[unused391]', '[unused392]', '[unused393]', '[unused394]', '[unused395]', '[unused396]', '[unused397]', '[unused398]', '[unused399]', '[unused400]', '[unused401]', '[unused402]', '[unused403]', '[unused404]', '[unused405]', '[unused406]', '[unused407]', '[unused408]', '[unused409]', '[unused410]', '[unused411]', '[unused412]', '[unused413]', '[unused414]', '[unused415]', '[unused416]', '[unused417]', '[unused418]', '[unused419]', '[unused420]', '[unused421]', '[unused422]', '[unused423]', '[unused424]', '[unused425]', '[unused426]', '[unused427]', '[unused428]', '[unused429]', '[unused430]', '[unused431]', '[unused432]', '[unused433]', '[unused434]', '[unused435]', '[unused436]', '[unused437]', '[unused438]', '[unused439]', '[unused440]', '[unused441]', '[unused442]', '[unused443]', '[unused444]', '[unused445]', '[unused446]', '[unused447]', '[unused448]', '[unused449]', '[unused450]', '[unused451]', '[unused452]', '[unused453]', '[unused454]', '[unused455]', '[unused456]', '[unused457]', '[unused458]', '[unused459]', '[unused460]', '[unused461]', '[unused462]', '[unused463]', '[unused464]', '[unused465]', '[unused466]', '[unused467]', '[unused468]', '[unused469]', '[unused470]', '[unused471]', '[unused472]', '[unused473]', '[unused474]', '[unused475]', '[unused476]', '[unused477]', '[unused478]', '[unused479]', '[unused480]', '[unused481]', '[unused482]', '[unused483]', '[unused484]', '[unused485]', '[unused486]', '[unused487]', '[unused488]', '[unused489]', '[unused490]', '[unused491]', '[unused492]', '[unused493]', '[unused494]', '[unused495]', '[unused496]', '[unused497]', '[unused498]', '[unused499]', '[unused500]', '[unused501]', '[unused502]', '[unused503]', '[unused504]', '[unused505]', '[unused506]', '[unused507]', '[unused508]', '[unused509]', '[unused510]', '[unused511]', '[unused512]', '[unused513]', '[unused514]', '[unused515]', '[unused516]', '[unused517]', '[unused518]', '[unused519]', '[unused520]', '[unused521]', '[unused522]', '[unused523]', '[unused524]', '[unused525]', '[unused526]', '[unused527]', '[unused528]', '[unused529]', '[unused530]', '[unused531]', '[unused532]', '[unused533]', '[unused534]', '[unused535]', '[unused536]', '[unused537]', '[unused538]', '[unused539]', '[unused540]', '[unused541]', '[unused542]', '[unused543]', '[unused544]', '[unused545]', '[unused546]', '[unused547]', '[unused548]', '[unused549]', '[unused550]', '[unused551]', '[unused552]', '[unused553]', '[unused554]', '[unused555]', '[unused556]', '[unused557]', '[unused558]', '[unused559]', '[unused560]', '[unused561]', '[unused562]', '[unused563]', '[unused564]', '[unused565]', '[unused566]', '[unused567]', '[unused568]', '[unused569]', '[unused570]', '[unused571]', '[unused572]', '[unused573]', '[unused574]', '[unused575]', '[unused576]', '[unused577]', '[unused578]', '[unused579]', '[unused580]', '[unused581]', '[unused582]', '[unused583]', '[unused584]', '[unused585]', '[unused586]', '[unused587]', '[unused588]', '[unused589]', '[unused590]', '[unused591]', '[unused592]', '[unused593]', '[unused594]', '[unused595]', '[unused596]', '[unused597]', '[unused598]', '[unused599]', '[unused600]', '[unused601]', '[unused602]', '[unused603]', '[unused604]', '[unused605]', '[unused606]', '[unused607]', '[unused608]', '[unused609]', '[unused610]', '[unused611]', '[unused612]', '[unused613]', '[unused614]', '[unused615]', '[unused616]', '[unused617]', '[unused618]', '[unused619]', '[unused620]', '[unused621]', '[unused622]', '[unused623]', '[unused624]', '[unused625]', '[unused626]', '[unused627]', '[unused628]', '[unused629]', '[unused630]', '[unused631]', '[unused632]', '[unused633]', '[unused634]', '[unused635]', '[unused636]', '[unused637]', '[unused638]', '[unused639]', '[unused640]', '[unused641]', '[unused642]', '[unused643]', '[unused644]', '[unused645]', '[unused646]', '[unused647]', '[unused648]', '[unused649]', '[unused650]', '[unused651]', '[unused652]', '[unused653]', '[unused654]', '[unused655]', '[unused656]', '[unused657]', '[unused658]', '[unused659]', '[unused660]', '[unused661]', '[unused662]', '[unused663]', '[unused664]', '[unused665]', '[unused666]', '[unused667]', '[unused668]', '[unused669]', '[unused670]', '[unused671]', '[unused672]', '[unused673]', '[unused674]', '[unused675]', '[unused676]', '[unused677]', '[unused678]', '[unused679]', '[unused680]', '[unused681]', '[unused682]', '[unused683]', '[unused684]', '[unused685]', '[unused686]', '[unused687]', '[unused688]', '[unused689]', '[unused690]', '[unused691]', '[unused692]', '[unused693]', '[unused694]', '[unused695]', '[unused696]', '[unused697]', '[unused698]', '[unused699]', '[unused700]', '[unused701]', '[unused702]', '[unused703]', '[unused704]', '[unused705]', '[unused706]', '[unused707]', '[unused708]', '[unused709]', '[unused710]', '[unused711]', '[unused712]', '[unused713]', '[unused714]', '[unused715]', '[unused716]', '[unused717]', '[unused718]', '[unused719]', '[unused720]', '[unused721]', '[unused722]', '[unused723]', '[unused724]', '[unused725]', '[unused726]', '[unused727]', '[unused728]', '[unused729]', '[unused730]', '[unused731]', '[unused732]', '[unused733]', '[unused734]', '[unused735]', '[unused736]', '[unused737]', '[unused738]', '[unused739]', '[unused740]', '[unused741]', '[unused742]', '[unused743]', '[unused744]', '[unused745]', '[unused746]', '[unused747]', '[unused748]', '[unused749]', '[unused750]', '[unused751]', '[unused752]', '[unused753]', '[unused754]', '[unused755]', '[unused756]', '[unused757]', '[unused758]', '[unused759]', '[unused760]', '[unused761]', '[unused762]', '[unused763]', '[unused764]', '[unused765]', '[unused766]', '[unused767]', '[unused768]', '[unused769]', '[unused770]', '[unused771]', '[unused772]', '[unused773]', '[unused774]', '[unused775]', '[unused776]', '[unused777]', '[unused778]', '[unused779]', '[unused780]', '[unused781]', '[unused782]', '[unused783]', '[unused784]', '[unused785]', '[unused786]', '[unused787]', '[unused788]', '[unused789]', '[unused790]', '[unused791]', '[unused792]', '[unused793]', '[unused794]', '[unused795]', '[unused796]', '[unused797]', '[unused798]', '[unused799]', '[unused800]', '[unused801]', '[unused802]', '[unused803]', '[unused804]', '[unused805]', '[unused806]', '[unused807]', '[unused808]', '[unused809]', '[unused810]', '[unused811]', '[unused812]', '[unused813]', '[unused814]', '[unused815]', '[unused816]', '[unused817]', '[unused818]', '[unused819]', '[unused820]', '[unused821]', '[unused822]', '[unused823]', '[unused824]', '[unused825]', '[unused826]', '[unused827]', '[unused828]', '[unused829]', '[unused830]', '[unused831]', '[unused832]', '[unused833]', '[unused834]', '[unused835]', '[unused836]', '[unused837]', '[unused838]', '[unused839]', '[unused840]', '[unused841]', '[unused842]', '[unused843]', '[unused844]', '[unused845]', '[unused846]', '[unused847]', '[unused848]', '[unused849]', '[unused850]', '[unused851]', '[unused852]', '[unused853]', '[unused854]', '[unused855]', '[unused856]', '[unused857]', '[unused858]', '[unused859]', '[unused860]', '[unused861]', '[unused862]', '[unused863]', '[unused864]', '[unused865]', '[unused866]', '[unused867]', '[unused868]', '[unused869]', '[unused870]', '[unused871]', '[unused872]', '[unused873]', '[unused874]', '[unused875]', '[unused876]', '[unused877]', '[unused878]', '[unused879]', '[unused880]', '[unused881]', '[unused882]', '[unused883]', '[unused884]', '[unused885]', '[unused886]', '[unused887]', '[unused888]', '[unused889]', '[unused890]', '[unused891]', '[unused892]', '[unused893]', '[unused894]', '[unused895]', '[unused896]', '[unused897]', '[unused898]', '[unused899]', '[unused900]', '[unused901]', '[unused902]', '[unused903]', '[unused904]', '[unused905]', '[unused906]', '[unused907]', '[unused908]', '[unused909]', '[unused910]', '[unused911]', '[unused912]', '[unused913]', '[unused914]', '[unused915]', '[unused916]', '[unused917]', '[unused918]', '[unused919]', '[unused920]', '[unused921]', '[unused922]', '[unused923]', '[unused924]', '[unused925]', '[unused926]', '[unused927]', '[unused928]', '[unused929]', '[unused930]', '[unused931]', '[unused932]', '[unused933]', '[unused934]', '[unused935]', '[unused936]', '[unused937]', '[unused938]', '[unused939]', '[unused940]', '[unused941]', '[unused942]', '[unused943]', '[unused944]', '[unused945]', '[unused946]', '[unused947]', '[unused948]', '[unused949]', '[unused950]', '[unused951]', '[unused952]', '[unused953]', '[unused954]', '[unused955]', '[unused956]', '[unused957]', '[unused958]', '[unused959]', '[unused960]', '[unused961]', '[unused962]', '[unused963]', '[unused964]', '[unused965]', '[unused966]', '[unused967]', '[unused968]', '[unused969]', '[unused970]', '[unused971]', '[unused972]', '[unused973]', '[unused974]', '[unused975]', '[unused976]', '[unused977]', '[unused978]', '[unused979]', '[unused980]', '[unused981]', '[unused982]', '[unused983]', '[unused984]', '[unused985]', '[unused986]', '[unused987]', '[unused988]', '[unused989]', '[unused990]', '[unused991]', '[unused992]', '[unused993]', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', '©', 'ª', '«', '¬', '®', '°', '±', '²', '³', '´', 'µ', '¶', '·', '¹', 'º', '»', '¼', '½', '¾', '¿', '×', 'ß', 'æ', 'ð', '÷', 'ø', 'þ', 'đ', 'ħ', 'ı', 'ł', 'ŋ', 'œ', 'ƒ', 'ɐ', 'ɑ', 'ɒ', 'ɔ', 'ɕ', 'ə', 'ɛ', 'ɡ', 'ɣ', 'ɨ', 'ɪ', 'ɫ', 'ɬ', 'ɯ', 'ɲ', 'ɴ', 'ɹ', 'ɾ', 'ʀ', 'ʁ', 'ʂ', 'ʃ', 'ʉ', 'ʊ', 'ʋ', 'ʌ', 'ʎ', 'ʐ', 'ʑ', 'ʒ', 'ʔ', 'ʰ', 'ʲ', 'ʳ', 'ʷ', 'ʸ', 'ʻ', 'ʼ', 'ʾ', 'ʿ', 'ˈ', 'ː', 'ˡ', 'ˢ', 'ˣ', 'ˤ', 'α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ξ', 'ο', 'π', 'ρ', 'ς', 'σ', 'τ', 'υ', 'φ', 'χ', 'ψ', 'ω', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ђ', 'є', 'і', 'ј', 'љ', 'њ', 'ћ', 'ӏ', 'ա', 'բ', 'գ', 'դ', 'ե', 'թ', 'ի', 'լ', 'կ', 'հ', 'մ', 'յ', 'ն', 'ո', 'պ', 'ս', 'վ', 'տ', 'ր', 'ւ', 'ք', '־', 'א', 'ב', 'ג', 'ד', 'ה', 'ו', 'ז', 'ח', 'ט', 'י', 'ך', 'כ', 'ל', 'ם', 'מ', 'ן', 'נ', 'ס', 'ע', 'ף', 'פ', 'ץ', 'צ', 'ק', 'ר', 'ש', 'ת', '،', 'ء', 'ا', 'ب', 'ة', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ـ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ى', 'ي', 'ٹ', 'پ', 'چ', 'ک', 'گ', 'ں', 'ھ', 'ہ', 'ی', 'ے', 'अ', 'आ', 'उ', 'ए', 'क', 'ख', 'ग', 'च', 'ज', 'ट', 'ड', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'प', 'ब', 'भ', 'म', 'य', 'र', 'ल', 'व', 'श', 'ष', 'स', 'ह', 'ा', 'ि', 'ी', 'ो', '।', '॥', 'ং', 'অ', 'আ', 'ই', 'উ', 'এ', 'ও', 'ক', 'খ', 'গ', 'চ', 'ছ', 'জ', 'ট', 'ড', 'ণ', 'ত', 'থ', 'দ', 'ধ', 'ন', 'প', 'ব', 'ভ', 'ম', 'য', 'র', 'ল', 'শ', 'ষ', 'স', 'হ', 'া', 'ি', 'ী', 'ে', 'க', 'ச', 'ட', 'த', 'ந', 'ன', 'ப', 'ம', 'ய', 'ர', 'ல', 'ள', 'வ', 'ா', 'ி', 'ு', 'ே', 'ை', 'ನ', 'ರ', 'ಾ', 'ක', 'ය', 'ර', 'ල', 'ව', 'ා', 'ก', 'ง', 'ต', 'ท', 'น', 'พ', 'ม', 'ย', 'ร', 'ล', 'ว', 'ส', 'อ', 'า', 'เ', '་', '།', 'ག', 'ང', 'ད', 'ན', 'པ', 'བ', 'མ', 'འ', 'ར', 'ལ', 'ས', 'မ', 'ა', 'ბ', 'გ', 'დ', 'ე', 'ვ', 'თ', 'ი', 'კ', 'ლ', 'მ', 'ნ', 'ო', 'რ', 'ს', 'ტ', 'უ', 'ᄀ', 'ᄂ', 'ᄃ', 'ᄅ', 'ᄆ', 'ᄇ', 'ᄉ', 'ᄊ', 'ᄋ', 'ᄌ', 'ᄎ', 'ᄏ', 'ᄐ', 'ᄑ', 'ᄒ', 'ᅡ', 'ᅢ', 'ᅥ', 'ᅦ', 'ᅧ', 'ᅩ', 'ᅪ', 'ᅭ', 'ᅮ', 'ᅯ', 'ᅲ', 'ᅳ', 'ᅴ', 'ᅵ', 'ᆨ', 'ᆫ', 'ᆯ', 'ᆷ', 'ᆸ', 'ᆼ', 'ᴬ', 'ᴮ', 'ᴰ', 'ᴵ', 'ᴺ', 'ᵀ', 'ᵃ', 'ᵇ', 'ᵈ', 'ᵉ', 'ᵍ', 'ᵏ', 'ᵐ', 'ᵒ', 'ᵖ', 'ᵗ', 'ᵘ', 'ᵢ', 'ᵣ', 'ᵤ', 'ᵥ', 'ᶜ', 'ᶠ', '‐', '‑', '‒', '–', '—', '―', '‖', '‘', '’', '‚', '“', '”', '„', '†', '‡', '•', '…', '‰', '′', '″', '›', '‿', '⁄', '⁰', 'ⁱ', '⁴', '⁵', '⁶', '⁷', '⁸', '⁹', '⁺', '⁻', 'ⁿ', '₀', '₁', '₂', '₃', '₄', '₅', '₆', '₇', '₈', '₉', '₊', '₍', '₎', 'ₐ', 'ₑ', 'ₒ', 'ₓ', 'ₕ', 'ₖ', 'ₗ', 'ₘ', 'ₙ', 'ₚ', 'ₛ', 'ₜ', '₤', '₩', '€', '₱', '₹', 'ℓ', '№', 'ℝ', '™', '⅓', '⅔', '←', '↑', '→', '↓', '↔', '↦', '⇄', '⇌', '⇒', '∂', '∅', '∆', '∇', '∈', '−', '∗', '∘', '√', '∞', '∧', '∨', '∩', '∪', '≈', '≡', '≤', '≥', '⊂', '⊆', '⊕', '⊗', '⋅', '─', '│', '■', '▪', '●', '★', '☆', '☉', '♠', '♣', '♥', '♦', '♭', '♯', '⟨', '⟩', 'ⱼ', '⺩', '⺼', '⽥', '、', '。', '〈', '〉', '《', '》', '「', '」', '『', '』', '〜', 'あ', 'い', 'う', 'え', 'お', 'か', 'き', 'く', 'け', 'こ', 'さ', 'し', 'す', 'せ', 'そ', 'た', 'ち', 'っ', 'つ', 'て', 'と', 'な', 'に', 'ぬ', 'ね', 'の', 'は', 'ひ', 'ふ', 'へ', 'ほ', 'ま', 'み', 'む', 'め', 'も', 'や', 'ゆ', 'よ', 'ら', 'り', 'る', 'れ', 'ろ', 'を', 'ん', 'ァ', 'ア', 'ィ', 'イ', 'ウ', 'ェ', 'エ', 'オ', 'カ', 'キ', 'ク', 'ケ', 'コ', 'サ', 'シ', 'ス', 'セ', 'タ', 'チ', 'ッ', 'ツ', 'テ', 'ト', 'ナ', 'ニ', 'ノ', 'ハ', 'ヒ', 'フ', 'ヘ', 'ホ', 'マ', 'ミ', 'ム', 'メ', 'モ', 'ャ', 'ュ', 'ョ', 'ラ', 'リ', 'ル', 'レ', 'ロ', 'ワ', 'ン', '・', 'ー', '一', '三', '上', '下', '不', '世', '中', '主', '久', '之', '也', '事', '二', '五', '井', '京', '人', '亻', '仁', '介', '代', '仮', '伊', '会', '佐', '侍', '保', '信', '健', '元', '光', '八', '公', '内', '出', '分', '前', '劉', '力', '加', '勝', '北', '区', '十', '千', '南', '博', '原', '口', '古', '史', '司', '合', '吉', '同', '名', '和', '囗', '四', '国', '國', '土', '地', '坂', '城', '堂', '場', '士', '夏', '外', '大', '天', '太', '夫', '奈', '女', '子', '学', '宀', '宇', '安', '宗', '定', '宣', '宮', '家', '宿', '寺', '將', '小', '尚', '山', '岡', '島', '崎', '川', '州', '巿', '帝', '平', '年', '幸', '广', '弘', '張', '彳', '後', '御', '德', '心', '忄', '志', '忠', '愛', '成', '我', '戦', '戸', '手', '扌', '政', '文', '新', '方', '日', '明', '星', '春', '昭', '智', '曲', '書', '月', '有', '朝', '木', '本', '李', '村', '東', '松', '林', '森', '楊', '樹', '橋', '歌', '止', '正', '武', '比', '氏', '民', '水', '氵', '氷', '永', '江', '沢', '河', '治', '法', '海', '清', '漢', '瀬', '火', '版', '犬', '王', '生', '田', '男', '疒', '発', '白', '的', '皇', '目', '相', '省', '真', '石', '示', '社', '神', '福', '禾', '秀', '秋', '空', '立', '章', '竹', '糹', '美', '義', '耳', '良', '艹', '花', '英', '華', '葉', '藤', '行', '街', '西', '見', '訁', '語', '谷', '貝', '貴', '車', '軍', '辶', '道', '郎', '郡', '部', '都', '里', '野', '金', '鈴', '镇', '長', '門', '間', '阝', '阿', '陳', '陽', '雄', '青', '面', '風', '食', '香', '馬', '高', '龍', '龸', 'ﬁ', 'ﬂ', '！', '（', '）', '，', '－', '．', '／', '：', '？', '～', 'the', 'of', 'and', 'in', 'to', 'was', 'he', 'is', 'as', 'for', 'on', 'with', 'that', 'it', 'his', 'by', 'at', 'from', 'her', '##s', 'she', 'you', 'had', 'a

In [ ]:
tokenizer.vocab_size

# tokenizer.vocab ==== enterire words with index
# tokenizer.vocab.keys() ==== only words
# tokenizer.vocab_size

30522

In [ ]:
tokenizer.vocab['bed'],tokenizer.vocab['##bed']

(2793, 8270)

In [ ]:
tokenizer.tokenize('embeddings')

['em', '##bed', '##ding', '##s']

In [ ]:
# we did
tokenizer.vocab['em'],tokenizer.vocab['##bed'],tokenizer.vocab['##ding'],tokenizer.vocab['##s']
#embeddings= em+bed+ding+s
#embeddings is not available
# embeddings =[em,##bed,##ding,##s] =[7861,8270,4667,2015]

(7861, 8270, 4667, 2015)

In [ ]:
tokenizer.vocab['bed']

2793

In [ ]:
tokenizer.tokenize('embeddings'),tokenizer.convert_tokens_to_ids(['em','##bed','##ding','##s'])

(['em', '##bed', '##ding', '##s'], [7861, 8270, 4667, 2015])

In [ ]:
tokenizer.convert_ids_to_tokens([7861,8270,4667,2015])

['em', '##bed', '##ding', '##s']

In [ ]:
tokenizer.convert_tokens_to_string(['em','##bed','##ding','##s'])

'embeddings'

In [ ]:
tokenizer.convert_tokens_to_ids(['em','##bed','##ding','##s'])
tokenizer.convert_ids_to_tokens([7861,8270,4667,2015])
tokenizer.convert_tokens_to_string(['em','##bed','##ding','##s'])

'embeddings'

**uncased means No Case sesitive**

In [ ]:
tokenizer.vocab['machine']

3698

In [ ]:
tokenizer.vocab['Machine'] # error

KeyError: 'Machine'

In [ ]:
tokenizer.tokenize('machine'),tokenizer.convert_tokens_to_ids('machine')

(['machine'], 3698)

In [ ]:
tokenizer.tokenize('Machine'),tokenizer.convert_tokens_to_ids('Machine')
# In vocabulary the word 'Machine' not there
# UNK token id availabe

(['machine'], 100)

In [ ]:
tokenizer.vocab['hello'],tokenizer.vocab['##～']

(7592, 30521)

In [ ]:
tokenizer.vocab['we'],tokenizer.vocab['are'],tokenizer.vocab['learning'],tokenizer.vocab['bert']

(2057, 2024, 4083, 14324)

In [ ]:
print(tokenizer.vocab['##bed']) # For combining
print(tokenizer.vocab['bed'])  # Normal
print(tokenizer.vocab['##ding'])

8270
2793
4667

**tokenizer.tokenize**

- we are tokenize the sentences into words

In [ ]:
sentence='we are learning bert embeddings'
tokens=tokenizer.tokenize(sentence)
tokens

['we', 'are', 'learning', 'bert', 'em', '##bed', '##ding', '##s']

In [ ]:
sentence1='hello how are you'
tokens=tokenizer.tokenize(sentence1)
tokens

['hello', 'how', 'are', 'you']

In [ ]:
sen2='we are learning bert embeddings.It is interesting'
tokens=tokenizer.tokenize(sen2)
tokens

['we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '##s',
 '.',
 'it',
 'is',
 'interesting']

In [ ]:
# GenAI word is not available in vocabulary
# but BERT model divide the GenAi into with
tokenizer.tokenize('GenAI')

['gen', '##ai']

In [ ]:
tokenizer.tokenize('embeddings')

['em', '##bed', '##ding', '##s']

In [ ]:
tokenizer.tokenize('moye moye')

['mo', '##ye', 'mo', '##ye']

In [ ]:
sentence='we are learning bert embeddings'
tokenizer.tokenize(sentence)

['we', 'are', 'learning', 'bert', 'em', '##bed', '##ding', '##s']

In [ ]:
tokenizer.tokenize('machine')

['machine']

In [ ]:
tokenizer.tokenize('Machine') # M === > m  model name: uncased

['machine']

In [ ]:
tokenizer.tokenize('machine learning')

['machine', 'learning']

- whenever we apply tokenize it tries to get the combination of words from vocabuary

- For example **machine learning** is not available in vocabulary

- But mcahine and learning is there

- So it will give two words

- **Machinelearning** is also not there, it tries to break the words

- The breaking words inthe form of # symbol

In [ ]:
tokens=tokenizer.tokenize('Machinelearning')
tokens

['machine', '##lea', '##rn', '##ing']

# Sentence tokenize

In [ ]:
sentence='we are learning bert embeddings'
tokens=tokenizer.tokenize(sentence)
tokens

['we', 'are', 'learning', 'bert', 'em', '##bed', '##ding', '##s']

In [ ]:
tokens

['we', 'are', 'learning', 'bert', 'em', '##bed', '##ding', '##s']

In [ ]:
# two tokens we need to add to convey that two or more senteces
# cls  and sep

# ['CLS'], '[CLS]'

tokens1=['[CLS]']+tokens+['[SEP]']  #  "[CLS]"
tokens1
# generally CLS AT STARTING ONLY , NOT AT ENDING

# model will takecare all these things automatically

['[CLS]',
 'we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '##s',
 '[SEP]']

In [ ]:
#tokens2=['[cls]']+tokens+['[sep]']
#tokens2 # generally we take CLS and SEP

**Add the Pad tokens**

In [ ]:
tokens2=['[CLS]']+tokens+['[SEP]']+['[PAD]']+['[PAD]']
tokens2
# l1+l2+l3
# every sentence vector should be in equal length
# we need to pad
# here im not adding 512, Im giving an idea how model will add the pad tokens

['[CLS]',
 'we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '##s',
 '[SEP]',
 '[PAD]',
 '[PAD]']

In [ ]:
#tokenizer(sentence)  #model is giving

In [ ]:
token_ids=tokenizer.convert_tokens_to_ids(tokens2)
token_ids

[101, 2057, 2024, 4083, 14324, 7861, 8270, 4667, 2015, 102, 0, 0]

**Attention mask**

- Token is present read as 1

- PAD token read as 0

In [ ]:
#attention_mask where ever tokens present =1 for pad tokens zero
# pads are use to match token length only
attention_mask=[1 if i!='[PAD]' else 0 for i in tokens2]
attention_mask

# this is very fundamental concept in bert

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]

- Fisrt we get the tokens

- Next we added extra tokens like CLS,SEP and PAD

- Then we are creating an attention mask : which has 1 and 0

## get the token ids

- we need to retrive the index of each token based on vocab

In [ ]:
dir(tokenizer)

['SPECIAL_TOKENS_ATTRIBUTES',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_tokens',
 '_added_tokens_decoder',
 '_added_tokens_encoder',
 '_auto_class',
 '_batch_encode_plus',
 '_batch_prepare_for_model',
 '_call_one',
 '_convert_id_to_token',
 '_convert_token_to_id',
 '_convert_token_to_id_with_added_voc',
 '_create_repo',
 '_decode',
 '_decode_use_source_tokenizer',
 '_encode_plus',
 '_eventual_warn_about_too_long_sequence',
 '_eventually_correct_t5_max_length',
 '_from_pretrained',
 '_get_files_timestamps',
 '_get_padding_truncation_strategies',
 '_in_target_context_manager',
 '_pad',
 '_pad_token_type_id',
 '_processor_class',
 '_save_pretrained',
 '_set_model_specific_special_tokens',
 '_set_processor_class',
 '_special_tokens_map',
 '_switch_to_input_mode',
 '_switch_to_target_mode',
 '_tokenize',
 '_update_total_vocab_size',
 '_update_trie',
 '_upload_modified_files',
 'add_special_tokens',
 'add_tokens',
 'added_tokens_decoder',
 'added_tokens_encoder',
 'all_special_ids',
 'all_special_tokens',
 'all_special_tokens_extended',
 'apply_chat_template',
 'as_target_tokenizer',
 'basic_tokenizer',
 'batch_decode',
 'batch_encode_plus',
 'build_inputs_with_special_tokens',
 'chat_template',
 'clean_up_tokenization',
 'clean_up_tokenization_spaces',
 'convert_added_tokens',
 'convert_ids_to_tokens',
 'convert_tokens_to_ids',
 'convert_tokens_to_string',
 'create_token_type_ids_from_sequences',
 'decode',
 'deprecation_warnings',
 'do_basic_tokenize',
 'do_lower_case',
 'encode',
 'encode_message_with_chat_template',
 'encode_plus',
 'extra_special_tokens',
 'from_pretrained',
 'get_added_vocab',
 'get_chat_template',
 'get_special_tokens_mask',
 'get_vocab',
 'ids_to_tokens',
 'init_inputs',
 'init_kwargs',
 'is_fast',
 'max_len_sentences_pair',
 'max_len_single_sentence',
 'model_input_names',
 'model_max_length',
 'name_or_path',
 'num_special_tokens_to_add',
 'pad',
 'pad_token_type_id',
 'padding_side',
 'prepare_for_model',
 'prepare_for_tokenization',
 'prepare_seq2seq_batch',
 'pretrained_vocab_files_map',
 'push_to_hub',
 'register_for_auto_class',
 'sanitize_special_tokens',
 'save_chat_templates',
 'save_pretrained',
 'save_vocabulary',
 'slow_tokenizer_class',
 'special_tokens_map',
 'special_tokens_map_extended',
 'split_special_tokens',
 'tokenize',
 'tokens_trie',
 'total_vocab_size',
 'truncate_sequences',
 'truncation_side',
 'verbose',
 'vocab',
 'vocab_files_names',
 'vocab_size',
 'wordpiece_tokenizer']

In [ ]:
tokens2

['[CLS]',
 'we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '##s',
 '[SEP]',
 '[PAD]',
 '[PAD]']

In [ ]:
tokenizer.vocab['we']

2057

In [ ]:
ids=tokenizer.convert_tokens_to_ids(tokens2)
ids

[101, 2057, 2024, 4083, 14324, 7861, 8270, 4667, 2015, 102, 0, 0]

In [ ]:
tokenizer.convert_ids_to_tokens(ids)

['[CLS]',
 'we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '##s',
 '[SEP]',
 '[PAD]',
 '[PAD]']

In [ ]:
tokenizer.convert_tokens_to_string(tokens2)

'[CLS] we are learning bert embeddings [SEP] [PAD] [PAD]'

In [ ]:
tokenizer.convert_tokens_to_ids(tokens2)
tokenizer.convert_tokens_to_string(tokens2)
tokenizer.convert_ids_to_tokens(ids)

['[CLS]',
 'we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '##s',
 '[SEP]',
 '[PAD]',
 '[PAD]']

In [ ]:
dir(tokenizer)
#convert_ids_to_tokens',
#'convert_tokens_to_ids',
#'convert_tokens_to_string',

['SPECIAL_TOKENS_ATTRIBUTES',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_tokens',
 '_added_tokens_decoder',
 '_added_tokens_encoder',
 '_auto_class',
 '_batch_encode_plus',
 '_batch_prepare_for_model',
 '_call_one',
 '_convert_id_to_token',
 '_convert_token_to_id',
 '_convert_token_to_id_with_added_voc',
 '_create_repo',
 '_decode',
 '_decode_use_source_tokenizer',
 '_encode_plus',
 '_eventual_warn_about_too_long_sequence',
 '_eventually_correct_t5_max_length',
 '_from_pretrained',
 '_get_files_timestamps',
 '_get_padding_truncation_strategies',
 '_in_target_context_manager',
 '_pad',
 '_pad_token_type_id',
 '_processor_class',
 '_save_pretrained',
 '_set_model_specific_special_tokens',
 '_set_processor_class',
 '_special_tokens_map',
 '_switch_to_input_mode',
 '_switch_to_target_mode',
 '_tokenize',
 '_update_total_vocab_size',
 '_update_trie',
 '_upload_modified_files',
 'add_special_tokens',
 'add_tokens',
 'added_tokens_decoder',
 'added_tokens_encoder',
 'all_special_ids',
 'all_special_tokens',
 'all_special_tokens_extended',
 'apply_chat_template',
 'as_target_tokenizer',
 'basic_tokenizer',
 'batch_decode',
 'batch_encode_plus',
 'build_inputs_with_special_tokens',
 'chat_template',
 'clean_up_tokenization',
 'clean_up_tokenization_spaces',
 'convert_added_tokens',
 'convert_ids_to_tokens',
 'convert_tokens_to_ids',
 'convert_tokens_to_string',
 'create_token_type_ids_from_sequences',
 'decode',
 'deprecation_warnings',
 'do_basic_tokenize',
 'do_lower_case',
 'encode',
 'encode_message_with_chat_template',
 'encode_plus',
 'extra_special_tokens',
 'from_pretrained',
 'get_added_vocab',
 'get_chat_template',
 'get_special_tokens_mask',
 'get_vocab',
 'ids_to_tokens',
 'init_inputs',
 'init_kwargs',
 'is_fast',
 'max_len_sentences_pair',
 'max_len_single_sentence',
 'model_input_names',
 'model_max_length',
 'name_or_path',
 'num_special_tokens_to_add',
 'pad',
 'pad_token_type_id',
 'padding_side',
 'prepare_for_model',
 'prepare_for_tokenization',
 'prepare_seq2seq_batch',
 'pretrained_vocab_files_map',
 'push_to_hub',
 'register_for_auto_class',
 'sanitize_special_tokens',
 'save_chat_templates',
 'save_pretrained',
 'save_vocabulary',
 'slow_tokenizer_class',
 'special_tokens_map',
 'special_tokens_map_extended',
 'split_special_tokens',
 'tokenize',
 'tokens_trie',
 'total_vocab_size',
 'truncate_sequences',
 'truncation_side',
 'verbose',
 'vocab',
 'vocab_files_names',
 'vocab_size',
 'wordpiece_tokenizer']

 'convert_ids_to_tokens',

 'convert_tokens_to_ids',

 'convert_tokens_to_string',

In [ ]:
token_ids=tokenizer.convert_tokens_to_ids(tokens2)
token_ids

[101, 2057, 2024, 4083, 14324, 7861, 8270, 4667, 2015, 102, 0, 0]

when sentence is equal to 512 padding is required or not sir..

sentence words >512

words=512

words<512

Truncate=True pad=True

In [ ]:
tokenizer.convert_ids_to_tokens(token_ids)

['[CLS]',
 'we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '##s',
 '[SEP]',
 '[PAD]',
 '[PAD]']

In [ ]:
tokenizer.convert_tokens_to_string(tokens2)

'[CLS] we are learning bert embeddings [SEP] [PAD] [PAD]'

- If sentence is available divide into tokens

- Tokens to token ids

- Suppose we have token ids then we can get tokens

- Suppose we have tokesn then we can get senetence

In [ ]:
#tokenizer.convert_ids_to_tokens(token_ids)

In [ ]:
#[101, 2057, 2024, 4083, 14324, 7861, 8270, 4667, 2015, 102, 0, 0]
tokenizer.vocab['we'],tokenizer.vocab['are'],tokenizer.vocab['learning']

(2057, 2024, 4083)

we have total 30522 tokens we have, which is our vocabulary

for each token we have one vector having 768 values

- Firstly we have sentence

- From sentence will get tokens(words)

- From tokens will get ids

- From ids we get the mask

- In order to get embeddings , we required token_ids and attention mask

- token ids are simply a list

- BERT model is py torch or tensorflow model

- list we need to convert into py torch or tensorflow format

In [ ]:
token_ids

# we don't want list type
# we want either array type ==== np
# or tensor type=== pt  or tf

[101, 2057, 2024, 4083, 14324, 7861, 8270, 4667, 2015, 102, 0, 0]

**we alreday got following from senetnece by manual way**

- tokens

- token ids

- attention mask

model tokenizer will take setence and provide a dictionary of output
with token ids and attenstion mask

- My loaded BERTModel variable name is : **model**

- My loaded BERTTokenizer variable name is : **tokenizer**

- now pass the senetnece which inside tokenizer model same

- It will give 3 outputs in dictionary

    - token ids that will match what we did till now

    - attention mask that also will match

    - token type ids

        - as we are passing only one senetence , so it wil provide all zeros

In [ ]:
tokenizer

BertTokenizer(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [ ]:
sentence

'we are learning bert embeddings'

In [ ]:
#help(tokenizer)

In [ ]:
tokenizer(sentence)
# We added pad but here model did not included padding

{'input_ids': [101, 2057, 2024, 4083, 14324, 7861, 8270, 4667, 2015, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
#help(tokenizer)

In [ ]:

import numpy as np
np.array(token_ids)

array([  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,  2015,
         102,     0,     0])

**unsqueeze**

- Convert 1D tensor to 2D

In [ ]:
token_ids

[101, 2057, 2024, 4083, 14324, 7861, 8270, 4667, 2015, 102, 0, 0]

In [ ]:
import torch
# token_ids is the variable has our tokens
torch.tensor(token_ids)

tensor([  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,  2015,   102,
            0,     0])

- we have seen alrady in ML

- recall how we pass a single input for prediction

- recall how we pass a test data for prediction

- it is in a format of list in list

- we passed the 2D data

- [[s1],[s2],[s3]]

In [ ]:
import torch
print(torch.tensor(token_ids)) # 1D
torch.tensor(token_ids).unsqueeze(0) # 2D

tensor([  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,  2015,   102,
            0,     0])

tensor([[  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,  2015,   102,
             0,     0]])

- We need to apply tensor format for both token ids as well as attention mask

- also we need to conver 1D to 2D for both token ids as well as attenstin mask

In [ ]:
import torch
torch.tensor(token_ids)  # 1D
torch.tensor(token_ids).unsqueeze(0) # 2D
torch.tensor(token_ids).reshape(1,-1) # 2D

tensor([[  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,  2015,   102,
             0,     0]])

In [ ]:
np.expand_dims(np.array([1,2,3,4]),axis=0)

array([[1, 2, 3, 4]])

In [ ]:
import torch
ids=torch.tensor(token_ids).unsqueeze(0)
mask=torch.tensor(attention_mask).unsqueeze(0)

In [ ]:
ids,mask

(tensor([[  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,  2015,   102,
              0,     0]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]]))

In [ ]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [ ]:
# our model variable name is : model

- model will take ids and attenstion mask as inputs

- model will give

    - each token embeddings

    - we have total 8 token other than spl token

    - each token emebdding of 768 vector length

    - so the shape is 8,768

    - we are passing one sentence so the shape is 1,8,768

    - we passed ids which has [CLS],[SEP] and two [PAD]

    - so the final shape is (1,12,768)

- model will give pooler output

    - which indicates sentence level embedding

    - here [CLS] token embeddings pass throuh dense layer + tanh

    - will provide one vectors which is nothing but a pooled vector

    - the whole sentence information stored in [CLS] Embedding

    - shape : (1,768)

In [ ]:
ids,attention_mask

(tensor([[  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,  2015,   102,
              0,     0]]),
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [ ]:
# tokenizer model variable
sentence='we are learning bert embeddings'
sentenc1="we are learning bert embeddings.It is interesting"
#
tokenizer(sentence)

{'input_ids': [101, 2057, 2024, 4083, 14324, 7861, 8270, 4667, 2015, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

## Truncation

In [ ]:
sentenc1="we are learning bert embeddings,It is interesting"
#
print(tokenizer.tokenize(sentenc1))
print(len(tokenizer.tokenize(sentenc1)))
outs=tokenizer(sentenc1,
          padding=True,
          max_length=8,
          truncation=True)
tokenizer.convert_ids_to_tokens(outs['input_ids'])

['we', 'are', 'learning', 'bert', 'em', '##bed', '##ding', '##s', ',', 'it', 'is', 'interesting']
12

['[CLS]', 'we', 'are', 'learning', 'bert', 'em', '##bed', '[SEP]']

## Padding

In [ ]:
sen1="we are learning bert embeddings" # 8 ===> 6  truncation
sen2="It is interesting"              # 4 === > 6  padding
sen=[sen1,sen2]
outs=tokenizer(sen,
          padding=True,
          max_length=6,
          truncation=True)
outs

{'input_ids': [[101, 2057, 2024, 4083, 14324, 102], [101, 2009, 2003, 5875, 102, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 0]]}

In [ ]:
tokenizer.convert_ids_to_tokens(outs['input_ids'][0])

['[CLS]', 'we', 'are', 'learning', 'bert', '[SEP]']

In [ ]:
tokenizer.convert_ids_to_tokens(outs['input_ids'][1])

['[CLS]', 'it', 'is', 'interesting', '[SEP]', '[PAD]']

**the above thing we did manually**

In [ ]:
ids,attention_mask

(tensor([[  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,  2015,   102,
              0,     0]]),
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [ ]:
# model variable name is model
out=model(ids,
          attention_mask=mask)
out

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.0092,  0.1259, -0.0047,  ..., -0.4423,  0.1906,  0.6233],
         [ 0.3883, -0.0681, -0.3392,  ..., -0.1198,  1.0829, -0.4945],
         [ 0.1727,  0.1222, -0.2289,  ..., -0.2507,  0.2388,  0.4446],
         ...,
         [ 0.5717,  0.2227, -0.3944,  ...,  0.1266, -0.7046, -0.2170],
         [-0.2574, -0.2615,  0.0443,  ...,  0.0920, -0.0838, -0.0943],
         [-0.2018, -0.2175,  0.0417,  ...,  0.0432, -0.1286, -0.0609]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.9170, -0.3431, -0.5738,  0.7184,  0.2774, -0.0901,  0.8430,  0.1892,
         -0.2136, -1.0000, -0.0374,  0.6389,  0.9881,  0.1148,  0.9344, -0.5937,
          0.1084, -0.4943,  0.2394, -0.5427,  0.6472,  0.9996,  0.5199,  0.2971,
          0.3666,  0.8450, -0.6475,  0.9381,  0.9606,  0.7622, -0.6632,  0.1369,
         -0.9893, -0.1750, -0.7070, -0.9922,  0.3434, -0.7639,  0.1226,  0.0986,
         -0.9186,  0.2575,  0.9999, -0.5148,  0.3140, -0.2090, -1.0000,  0.1931,
         -0.9005,  0.4248,  0.3755,  0.3924,  0.0979,  0.4084,  0.4009, -0.0047,
         -0.2242,  0.1171, -0.2254, -0.5230, -0.5921,  0.2967, -0.4044, -0.9114,
          0.2170,  0.0368,  0.0386, -0.2435, -0.1261, -0.1515,  0.8507,  0.2650,
          0.0603, -0.8321,  0.1317,  0.1692, -0.5126,  1.0000, -0.3662, -0.9794,
          0.5056,  0.1933,  0.3892,  0.3814,  0.0023, -1.0000,  0.4273, -0.0590,
         -0.9905,  0.0956,  0.4547, -0.0980,  0.2895,  0.5202, -0.3766, -0.3789,
         -0.2373, -0.3929, -0.1658, -0.2859,  0.0393, -0.1909, -0.2289, -0.3577,
          0.1611, -0.3033, -0.3601,  0.4292, -0.1784,  0.6555,  0.3502, -0.3023,
          0.3215, -0.9561,  0.4988, -0.2959, -0.9885, -0.4332, -0.9891,  0.7391,
          0.0571, -0.1636,  0.9592,  0.2091,  0.2804, -0.0187, -0.3533, -1.0000,
         -0.3503, -0.4947, -0.0036, -0.1603, -0.9803, -0.9637,  0.6033,  0.9634,
          0.1902,  0.9998, -0.2617,  0.9446,  0.1419, -0.2215, -0.2850, -0.3229,
          0.6890,  0.1149, -0.6517,  0.1188, -0.2362,  0.0166, -0.4627, -0.1895,
         -0.2916, -0.9306, -0.3465,  0.9499,  0.0303, -0.4702,  0.5532, -0.1544,
         -0.3615,  0.8685,  0.6084,  0.2023,  0.0018,  0.2921,  0.0072,  0.5078,
         -0.8717,  0.2800,  0.3708, -0.2363, -0.4612, -0.9821, -0.3352,  0.5186,
          0.9872,  0.7115,  0.2644,  0.4063, -0.2669,  0.3607, -0.9538,  0.9836,
         -0.0875,  0.1281, -0.1468,  0.2762, -0.8860, -0.1217,  0.8358, -0.3011,
         -0.8759,  0.0903, -0.4316, -0.3402, -0.5253,  0.5393, -0.2979, -0.3680,
          0.0158,  0.9287,  0.9697,  0.8162, -0.3322,  0.5624, -0.8870, -0.3041,
          0.1014,  0.2395,  0.0670,  0.9936, -0.5846, -0.0688, -0.9256, -0.9820,
         -0.1136, -0.8502,  0.0205, -0.7289,  0.5133, -0.1008, -0.0658,  0.2212,
         -0.9636, -0.7770,  0.2827, -0.3857,  0.4381, -0.3174,  0.6982,  0.6714,
         -0.5321,  0.5670,  0.9404, -0.3954, -0.7720,  0.7756, -0.2481,  0.8419,
         -0.5804,  0.9929,  0.5958,  0.5360, -0.9330, -0.3156, -0.8768, -0.1024,
         -0.0141, -0.3678,  0.3951,  0.5310,  0.3931,  0.6213, -0.4629,  0.9921,
         -0.6416, -0.9550, -0.2004, -0.1562, -0.9911,  0.4539,  0.2636,  0.0887,
         -0.4386, -0.5916, -0.9631,  0.8353,  0.0290,  0.9833, -0.2524, -0.8598,
         -0.4170, -0.9355, -0.1842, -0.1286,  0.3128, -0.1447, -0.9510,  0.4291,
          0.6074,  0.4235, -0.3043,  0.9951,  1.0000,  0.9777,  0.8977,  0.8796,
         -0.9978, -0.1393,  1.0000, -0.9278, -1.0000, -0.9412, -0.5011,  0.3638,
         -1.0000, -0.0150,  0.0855, -0.9124,  0.1251,  0.9808,  0.9811, -1.0000,
          0.9073,  0.9436, -0.5142,  0.6238, -0.3591,  0.9807,  0.4486,  0.5281,
         -0.1774,  0.3911, -0.7239, -0.8468, -0.0670, -0.1735,  0.9826,  0.0609,
         -0.7560, -0.9044,  0.2892, -0.0439, -0.2137, -0.9647, -0.1981, -0.1597,
          0.6793,  0.0156,  0.1599, -0.7306,  0.2779, -0.3135,  0.4557,  0.5967,
         -0.9555, -0.6852, -0.0995, -0.2932, -0.1497, -0.9701,  0.9689, -0.2457,
          0.3174,  1.0000,  0.0890, -0.8866,  0.4265,  0.1587, -0.4254,  1.0000,
          0.6360, -0.9849, -0.4571,  0.5203, -0.4822, -0.5299,  0.9995, -0.1683,
         -0.0511,  0.1223,  0.9789, -0.9923,  0.9631, -0.8604, -0.9687,  0.9596,
          0.9346, -0.1732, -0.7983, -0.0842, -0.4140,  0.1983, -0.9502,  0.5621,
          0.3450, -0.0946,  0.8788, -0.7655, -0.4833,  0.3553, -0.1108,  0.2928,
          0.7312,  0.4292, -0.2390, -0.0606, -0.1292, -0.2894, -0.9673,  0.2443,
          1.0000,  0.0216,  0.2138, -0.1447, -0.0380, -0.3126,  0.4249,  0.4516,
         -0.1613, -0.8928,  0.3059, -0.9000, -0.9901,  0.6889,  0.1109, -0.2631,
          0.9999,  0.3814,  0.1491,  0.0231,  0.8308, -0.0067,  0.5092,  0.1882,
          0.9774, -0.1999,  0.4768,  0.8222, -0.3709, -0.2304, -0.6133,  0.0019,
         -0.9435,  0.0568, -0.9553,  0.9651,  0.5249,  0.2971,  0.0809,  0.4362,
          1.0000, -0.5116,  0.5472, -0.1280,  0.7103, -0.9958, -0.7576, -0.2947,
          0.0387, -0.1640, -0.2781,  0.1769, -0.9688,  0.2834,  0.1790, -0.9609,
         -0.9908,  0.2219,  0.8051, -0.0455, -0.9137, -0.5841, -0.6491,  0.2114,
         -0.1939, -0.9062,  0.3515, -0.1530,  0.4776, -0.2415,  0.4977,  0.3065,
          0.8318, -0.5055, -0.1742, -0.0296, -0.7525,  0.6621, -0.8066, -0.5523,
         -0.0307,  1.0000, -0.3087,  0.7040,  0.7531,  0.6023, -0.1895,  0.1247,
          0.7366,  0.1684, -0.1430, -0.1690, -0.3798, -0.3592,  0.5698,  0.0681,
          0.1439,  0.7834,  0.6122,  0.1307,  0.0644, -0.1147,  0.9974, -0.1019,
         -0.0836, -0.5036, -0.1220, -0.1973, -0.2062,  1.0000,  0.3082,  0.4673,
         -0.9920, -0.3709, -0.9053,  1.0000,  0.8070, -0.8701,  0.5855,  0.3480,
         -0.0089,  0.6964, -0.1619, -0.1741,  0.0391,  0.0372,  0.9606, -0.4019,
         -0.9719, -0.7135,  0.3006, -0.9653,  0.9986, -0.5068, -0.2204, -0.2418,
          0.0145,  0.3337,  0.0408, -0.9805, -0.0315, -0.0382,  0.9648,  0.1435,
         -0.4691, -0.9330,  0.3043,  0.3601, -0.3581, -0.9370,  0.9738, -0.9719,
          0.4044,  1.0000,  0.3419, -0.4236,  0.0971, -0.3991,  0.2315, -0.0355,
          0.5607, -0.9527, -0.2543, -0.1488,  0.2671, -0.0941, -0.1932,  0.6867,
          0.1829, -0.4251, -0.5431,  0.0096,  0.3609,  0.8336, -0.1394, -0.0613,
          0.0737, -0.1221, -0.9165, -0.2595, -0.2719, -0.9998,  0.6017, -1.0000,
          0.0661, -0.2503, -0.2183,  0.8434,  0.3431,  0.4048, -0.7276, -0.1500,
          0.7567,  0.7551, -0.1797,  0.2094, -0.7248,  0.1841, -0.0638,  0.1933,
         -0.0661,  0.7329, -0.0658,  1.0000,  0.0184, -0.5485, -0.9429,  0.1870,
         -0.1393,  1.0000, -0.8482, -0.9560,  0.2601, -0.6492, -0.8524,  0.2117,
         -0.0387, -0.6602, -0.7319,  0.9502,  0.8296, -0.4941,  0.4455, -0.2592,
         -0.4219, -0.0331,  0.3951,  0.9877,  0.3977,  0.8979,  0.4787, -0.0871,
          0.9723,  0.2169,  0.4702,  0.0530,  1.0000,  0.3341, -0.9325,  0.3395,
         -0.9815, -0.1752, -0.9504,  0.1804,  0.1801,  0.8891, -0.1873,  0.9716,
         -0.3673,  0.0178, -0.0171,  0.2254,  0.3206, -0.9264, -0.9845, -0.9886,
          0.3515, -0.4000, -0.1061,  0.0874,  0.0368,  0.2655,  0.2839, -1.0000,
          0.9483,  0.4140,  0.3855,  0.9626,  0.4189,  0.4180,  0.1960, -0.9881,
         -0.9514, -0.3324, -0.2398,  0.7457,  0.5365,  0.8621,  0.1932, -0.4587,
         -0.3952, -0.0360, -0.4741, -0.9927,  0.3358,  0.1406, -0.9426,  0.9620,
         -0.3304, -0.0494,  0.4397, -0.4701,  0.9149,  0.8207,  0.3206,  0.0478,
          0.5111,  0.8987,  0.9433,  0.9898, -0.4366,  0.7624, -0.1626,  0.4944,
          0.6793, -0.9390,  0.0949,  0.3838, -0.1627,  0.2012, -0.1767, -0.9402,
          0.7245, -0.1391,  0.3720, -0.4198,  0.2343, -0.3615, -0.1499, -0.7891,
         -0.4696,  0.5113,  0.2501,  0.9242,  0.6579,  0.0512, -0.5967, -0.1129,
         -0.2055, -0.9326,  0.8764, -0.0072,  0.1569,  0.5175, -0.1248,  0.8671,
         -0.0397, -0.4081, -0.1848, -0.7505,  0.8653, -0.4784, -0.5467, -0.4394,
          0.6408,  0.2693,  0.9996, -0.3438, -0.4043, -0.3943, -0.2723,  0.3275,
         -0.3172, -1.0000,  0.2806, -0.0967,  0.4091, -0.1709,  0.4359, -0.0201,
         -0.9790, -0.2427,  0.5586,  0.2676, -0.4544, -0.3358,  0.5151,  0.2847,
          0.7951,  0.8682, -0.3876,  0.3629,  0.5653, -0.5545, -0.6577,  0.8920]],
       grad_fn=<TanhBackward0>), hidden_states=None, past_key_values=None, attentions=None, cross_attentions=None)

In [ ]:
len(out)

2

In [ ]:
ids
# 12 tokens
# each token 768
# we passed only one sentence 1
# 1,12,768

tensor([[  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,  2015,   102,
             0,     0]])

In [ ]:
out[0]

tensor([[[ 0.0092,  0.1259, -0.0047,  ..., -0.4423,  0.1906,  0.6233],
         [ 0.3883, -0.0681, -0.3392,  ..., -0.1198,  1.0829, -0.4945],
         [ 0.1727,  0.1222, -0.2289,  ..., -0.2507,  0.2388,  0.4446],
         ...,
         [ 0.5717,  0.2227, -0.3944,  ...,  0.1266, -0.7046, -0.2170],
         [-0.2574, -0.2615,  0.0443,  ...,  0.0920, -0.0838, -0.0943],
         [-0.2018, -0.2175,  0.0417,  ...,  0.0432, -0.1286, -0.0609]]],
       grad_fn=<NativeLayerNormBackward0>)

In [ ]:
out[0].shape
# 1   12   768

torch.Size([1, 12, 768])

In [ ]:
out[1].shape

torch.Size([1, 768])

In [ ]:
len(out[1][0])

768

In [ ]:
model

In [ ]:
len(out)

In [ ]:
# out[0] means hidden state outputs
out[0].shape
# 1 batch : one sentence
# 12 tokens : 12 tokens include SPL
# 768 vector length of each token

In [ ]:
out[1].shape
# Sentece vector

In [ ]:
out[0][0].detach().numpy()

array([[ 0.00922381,  0.12588218, -0.00472952, ..., -0.44231018,
         0.19055182,  0.6233031 ],
       [ 0.38827944, -0.06808041, -0.33917314, ..., -0.11978766,
         1.0828651 , -0.49452618],
       [ 0.17269301,  0.12221551, -0.22893909, ..., -0.2506715 ,
         0.23884769,  0.44455767],
       ...,
       [ 0.5717284 ,  0.2227499 , -0.39444903, ...,  0.12662402,
        -0.70461595, -0.21704525],
       [-0.25738037, -0.2615343 ,  0.04429096, ...,  0.09197848,
        -0.08379873, -0.09425116],
       [-0.20179984, -0.2174535 ,  0.04169652, ...,  0.04323951,
        -0.12858659, -0.06087786]], dtype=float32)

In [ ]:
tokens2

['[CLS]',
 'we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '##s',
 '[SEP]',
 '[PAD]',
 '[PAD]']

In [ ]:
out[0].ndim

3

In [ ]:
pd.DataFrame([[1,2,3],[10,20,30]])

    0   1   2
0   1   2   3
1  10  20  30

In [ ]:
import pandas as pd
pd.DataFrame(out[0][0].detach().numpy(),
             index=tokens2)

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
[CLS],0.009224,0.125882,-0.004730,-0.089249,-0.309873,-0.524943,0.297645,0.228629,0.035127,-0.331980,...,-0.087799,-0.204041,-0.041090,-0.116873,-0.043728,0.086987,-0.020280,-0.442310,0.190552,0.623303
we,0.388279,-0.068080,-0.339173,-0.228154,-0.327710,-0.568787,0.104046,0.725378,0.777292,-0.311463,...,0.413673,-0.019595,0.552768,-0.049934,-0.377344,0.369581,0.375544,-0.119788,1.082865,-0.494526
are,0.172693,0.122216,-0.228939,-0.711124,0.880530,-0.237058,0.082821,0.409708,0.015440,-1.228476,...,0.804260,-0.506891,0.554972,-0.287185,0.063107,0.619278,0.639668,-0.250672,0.238848,0.444558
learning,-0.683301,0.084550,0.054749,0.205972,0.165735,-0.430324,0.356466,0.438087,-0.150329,-0.747983,...,-0.304962,-0.358410,-0.543104,-0.636317,-0.139224,0.417709,0.378776,-0.525307,-0.081738,-0.000144
bert,0.221177,-0.028556,0.533576,-0.119218,-0.474573,0.024884,0.505081,-0.403581,0.044558,-0.513337,...,0.124315,0.067165,-0.591062,-0.063593,0.249766,0.335576,0.152941,-0.361477,-0.338109,0.174963
em,-0.247397,0.039750,-0.187946,-0.505387,0.095669,-0.165700,-0.637739,0.596646,0.079078,-0.110916,...,0.219998,-0.171279,-0.014698,-0.645431,-0.192556,0.449511,0.695518,-0.258275,-0.877591,0.516266
##bed,0.255884,-0.089450,-0.323035,-0.162606,0.048877,-0.523961,-0.132727,0.772660,1.049893,-0.529543,...,0.303247,0.094482,-0.136556,-0.618160,-0.144320,0.030916,0.429129,-0.058513,-0.504232,-0.159716
##ding,-0.417570,0.294297,-0.493644,-0.266223,0.292876,-0.399584,-0.174643,0.639105,0.483291,-0.002887,...,-0.135127,0.152184,-0.048708,-0.499568,-0.075192,0.181248,0.633204,-0.074910,-0.599574,0.593903
##s,-0.275189,-0.155669,-0.414321,-0.227724,0.171500,-0.492313,-0.044095,0.480055,-0.128881,-0.430279,...,0.582783,0.328843,-0.356209,-0.239973,-0.357055,-0.017807,0.783667,-0.049608,-0.545070,0.474257
[SEP],0.571728,0.222750,-0.394449,0.376921,-0.446457,-0.910466,0.421195,-0.909219,1.013358,-0.033854,...,0.194140,-0.070731,-0.412254,-0.668596,0.028954,-0.967503,0.217752,0.126624,-0.704616,-0.217045
[PAD],-0.257380,-0.261534,0.044291,0.037240,0.028523,-0.104530,0.215064,0.124924,0.277603,-0.850786,...,0.507233,0.098705,-0.351692,-0.216437,-0.332615,-0.259380,0.326739,0.091978,-0.083799,-0.094251
[PAD],-0.201800,-0.217453,0.041697,0.022347,0.007747,-0.133490,0.219756,0.164405,0.355572,-0.882363,...,0.512657,0.058769,-0.368811,-0.222528,-0.306331,-0.314992,0.365090,0.043240,-0.128587,-0.060878

**All Together**

In [ ]:
sentence='we are learning bert embeddings'
tokens=tokenizer.tokenize(sentence)
tokens

tokens1=['[CLS]']+tokens+['[SEP]']
tokens1

tokens2=['[CLS]']+tokens+['[SEP]']+['[PAD]']+['[PAD]']
tokens2

attention_mask=[1 if i!='[PAD]' else 0 for i in tokens2]
attention_mask

token_ids=tokenizer.convert_tokens_to_ids(tokens2)
token_ids


import torch
ids=torch.tensor(token_ids).unsqueeze(0)
mask=torch.tensor(attention_mask).unsqueeze(0)

out=model(ids,attention_mask=mask)
out

- Output will give two layers output

    - Hidden layer output

    - Pooler layer output

**Hidden layer output**

- Hidden layer will provide the Word embeddings of each word with 768 shape

- Here we are passing one sentence ,this sentence has 12 tokens each token vector size is 768

- the shape is (1,12,768)

**Pooler layers**

- Here BERT model will apply average pooling which gives average of all 12 token vectors values into a single vectors which has shape 768

In [ ]:
#out.items()
out.last_hidden_state
#out[0].shape

# we have 12 tokens are there
# this gives each token embeddvector
# vector has 768 , weights
# 1 batch
# 12 tokens
# 768 values
# 1,12,768

In [ ]:
out.last_hidden_state.shape
# out[0]

In [ ]:
ids

In [ ]:
out.pooler_output.shape
#out[1].shape

In [ ]:
out[0] # same as out.last_hidden_state
out[1] # same as out.pooler_output

In [ ]:
out[1][0][:10]



**setence_output** : Is simply an array (representation) of the last layer hidden representation of each token which will be of size (batch_size, seq_len, hidden_size)

**pooler_output:** Is representation/embedding of CLS token passed through some more layers Bertpooler, linear/dense and activation function. It is recommended to use this pooler_output as it contains contextualize information of whole sequence.

In [ ]:
import torch
from transformers import BertTokenizer, BertForMaskedLM

# Load pre-trained model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

# Example text with a masked token
text = "The cat sat on the [MASK]."

# Tokenize input text
tokenized_text = tokenizer.tokenize(text)
print("Tokenized text:", tokenized_text)

# Convert token to vocabulary indices
masked_index = tokenized_text.index('[MASK]')
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)

# Convert input to PyTorch tensors
tokens_tensor = torch.tensor([indexed_tokens])

# Predict all tokens
with torch.no_grad():
    outputs = model(tokens_tensor)
    predictions = outputs[0]

# Get the predicted token
predicted_index = torch.argmax(predictions[0, masked_index]).item()
predicted_token = tokenizer.convert_ids_to_tokens([predicted_index])[0]
print("Predicted token:", predicted_token)

NLP task
we need to focus how to convert a Text to numbers

this is called as WordEmbeddings

1.Bow
2.tf-idf
3.Word2Vec
4.BERT Transformers

BERT (Bidirectional Encoder Representations from Transformers)

Package name: Transformers
Developed by: Huggingface ==== Google
=========================================
Understanding the BERT models

1.install transformers
2.we need to import
   A) BertModel is used to access the Models(1M)
   B) BertTokenizer is used to access the vocab and    tokens
3. BertModel here we access
   model name: 'bert-base-uncased'

4. Input layer === Encoder layer === Pooler layer

5. the total tokens or words= 30522
6. the maximum sentence token size= 512
7. each token vector size = 768
8. Tokenizer has a vocab list
   A)which has token and its index
   B) 30522 tokens are available
   C) [PAD]
   D) [CLS]
   E) [SEP]
   D) [UNK]
   E) [MSK]
9) Best part here is
   when we want to divide a sentence into tokens
   A) first it will search is that word available in vocab list
   B) If it is not available
      it is try to tokenize the word with the tokens
      which is available in vocabulary list

   ex: 'moye' ==== >   'mo'+'#ye'

10) Any senetence can tokenize

11) Sentence= 'we are learning BERT Embeddings'

12) ['we','are','learning','BERT','EM','#bed','#dings']

13) Here we are adding some spl tokens [cls],[sep],[PAD]

14) ['[cls]','we','are','learning','BERT',
    'EM','#bed','#dings','[SEP]','[PAD]']

15) Attention mask:
     where ever [PAD] is make it as 0, other wise 1
    
16) Attention mask:[1,1,1,1,1,1,1,1,1,0]

17) Token ids: [101, 2057, 2024, 4083, 14324, 7861, 8270, 4667, 2015, 102, 0, 0]

18) In order to get the Vector we need to pass
    A) Attention mask of sentence
    B) TokenIds of sentence

19) The sentence has 7 words+3 spl tokens , we will get seven vectors
    each vector size is 768

    shape (10,768)

20) we will apply the pooler layer on 10 vectors finally we will get
    one sentence vectors

21) token ids should be in the form of
    either pytorch tensors
    or tensorflow tensors

   A) LIST ======== > [1,2,3,4]
   B) numpy array === >  array([1,2,3,4])
   C) Pytorch ===== > tensor([1,2,3,4])
   D) Tensorflow==== > tensor([1,2,3,4],dtype=int64)

In [ ]:
sen1="we are learning bert embeddings" # 8 ===> 6  truncation            # 4 === > 6  padding
outs=tokenizer(sen1,
          padding=True,
          max_length=6,
          truncation=True)
outs

{'input_ids': [101, 2057, 2024, 4083, 14324, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1]}

In [ ]:
def f1(**kwargs):
    print(kwargs)

f1(a=10,b=20)

{'a': 10, 'b': 20}

In [ ]:
def f1(*args):
    print(args)

f1(10,20)

(10, 20)

In [ ]:
f1(**{'a':10,'b':20})

{'a': 10, 'b': 20}

In [ ]:
#outs['input_ids']
#model(outs['input_ids'],outs['attention_mask'])
sen1="we are learning bert embeddings" # 8 ===> 6  truncation            # 4 === > 6  padding
outs=tokenizer(sen1,
          padding=True,
          max_length=6,
          truncation=True,
          return_tensors='pt')

model(**outs)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.1725,  0.4761,  0.0885,  ..., -0.2868,  0.2037,  0.0663],
         [ 0.9313,  0.3465,  0.0404,  ..., -0.0548,  1.3111, -0.7214],
         [ 0.9465,  0.3265,  0.1377,  ...,  0.0504,  0.1416,  0.0162],
         [ 0.0177, -0.4568,  0.5271,  ..., -0.2211,  0.2181, -0.5734],
         [ 0.1212, -0.3453,  0.0671,  ...,  0.4688,  0.3725, -0.5260],
         [ 1.0750,  0.1298, -0.1529,  ..., -0.0676, -0.7483, -0.3496]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.9322, -0.3969, -0.5126,  0.8295,  0.1144, -0.1225,  0.9370,  0.2964,
         -0.4108, -1.0000, -0.1600,  0.8364,  0.9844,  0.2456,  0.9560, -0.6535,
         -0.2519, -0.5760,  0.3534, -0.8105,  0.7477,  0.9988,  0.3541,  0.3466,
          0.4363,  0.9317, -0.6948,  0.9562,  0.9638,  0.7058, -0.8068,  0.1885,
         -0.9875, -0.1418, -0.5124, -0.9893,  0.3627, -0.7748,  0.0906,  0.0441,
         -0.9128,  0.2113,  0.9998, -0.1563,  0.2816, -0.3276, -1.0000,  0.2650,
         -0.8995,  0.5849,  0.4336,  0.2746,  0.1796,  0.4886,  0.4575,  0.0826,
         -0.1517,  0.1920, -0.1756, -0.5514, -0.5667,  0.3107, -0.6506, -0.8990,
          0.4896,  0.2189, -0.0784, -0.2215, -0.0736, -0.0786,  0.9234,  0.2365,
          0.0849, -0.8566,  0.2547,  0.1761, -0.5461,  1.0000, -0.5486, -0.9754,
          0.2668,  0.3123,  0.4301,  0.2043, -0.0320, -1.0000,  0.3701, -0.0772,
         -0.9908,  0.2617,  0.4478, -0.2115, -0.1024,  0.5526, -0.2686, -0.4407,
         -0.3722, -0.3519, -0.1816, -0.2745, -0.0056, -0.2662, -0.1423, -0.4134,
          0.2124, -0.4806, -0.6525,  0.4007, -0.0113,  0.7074,  0.3376, -0.3491,
          0.3925, -0.9626,  0.6739, -0.2712, -0.9878, -0.5513, -0.9898,  0.6506,
         -0.1944, -0.0691,  0.9703,  0.2138,  0.3447, -0.0692, -0.4902, -1.0000,
         -0.6460, -0.4364, -0.0121, -0.2058, -0.9792, -0.9554,  0.6170,  0.9669,
          0.1826,  0.9995, -0.3303,  0.9371, -0.1593, -0.2522,  0.2183, -0.4406,
          0.6477,  0.4575, -0.7405,  0.2567, -0.1924,  0.2278, -0.4983, -0.2836,
         -0.4016, -0.9472, -0.4117,  0.9610, -0.1350, -0.5648,  0.4246, -0.2544,
         -0.5364,  0.8628,  0.5360,  0.3890, -0.1215,  0.3449,  0.0420,  0.5895,
         -0.8736,  0.0580,  0.3890, -0.2978, -0.4027, -0.9762, -0.3941,  0.5680,
          0.9904,  0.8009,  0.2452,  0.5493, -0.2723,  0.6026, -0.9564,  0.9809,
         -0.2031,  0.2721,  0.1812, -0.0613, -0.8700, -0.1654,  0.9013, -0.5173,
         -0.8528,  0.0621, -0.4215, -0.4517, -0.3573,  0.5842, -0.3166, -0.4477,
         -0.1055,  0.9341,  0.9863,  0.8899, -0.2651,  0.7020, -0.9185, -0.4921,
          0.2424,  0.2817,  0.1156,  0.9944, -0.3879, -0.1783, -0.9512, -0.9860,
          0.0154, -0.9168, -0.0158, -0.7365,  0.5359,  0.2480,  0.3390,  0.4514,
         -0.9916, -0.8139,  0.4077, -0.3676,  0.4542, -0.3048,  0.3894,  0.6280,
         -0.5678,  0.8232,  0.8867, -0.2135, -0.7654,  0.8826, -0.3548,  0.8996,
         -0.6532,  0.9860,  0.6072,  0.6838, -0.9519, -0.1147, -0.9188, -0.3555,
         -0.0558, -0.3587,  0.5810,  0.5160,  0.3960,  0.7012, -0.6175,  0.9992,
         -0.4510, -0.9580,  0.4122, -0.4238, -0.9876,  0.5958,  0.2680, -0.2032,
         -0.4573, -0.6835, -0.9651,  0.9262,  0.1247,  0.9920, -0.0996, -0.9502,
         -0.4634, -0.9206, -0.1384, -0.2024,  0.0830, -0.1253, -0.9701,  0.4488,
          0.6156,  0.5221, -0.2049,  0.9991,  1.0000,  0.9752,  0.9052,  0.9322,
         -0.9944, -0.0803,  1.0000, -0.9468, -1.0000, -0.9455, -0.5800,  0.4925,
         -1.0000, -0.1239,  0.0256, -0.9241,  0.2702,  0.9784,  0.9963, -1.0000,
          0.8637,  0.9674, -0.5878,  0.8620, -0.2912,  0.9756,  0.3835,  0.4325,
         -0.2347,  0.2808, -0.5379, -0.9049, -0.1601, -0.0334,  0.9612,  0.1482,
         -0.7789, -0.9422,  0.1507, -0.1491, -0.1584, -0.9676, -0.1494,  0.2039,
          0.7094,  0.0995,  0.2176, -0.7825,  0.2380, -0.4436,  0.4762,  0.6412,
         -0.9458, -0.7678, -0.1692, -0.3690, -0.2005, -0.9520,  0.9682, -0.3326,
          0.5259,  1.0000,  0.0210, -0.9143,  0.4997,  0.2733, -0.2818,  1.0000,
          0.6801, -0.9793, -0.5090,  0.4611, -0.5038, -0.5844,  0.9990, -0.2345,
         -0.2149, -0.0965,  0.9639, -0.9907,  0.8966, -0.9363, -0.9735,  0.9610,
          0.9464, -0.2626, -0.6607,  0.0566, -0.4044,  0.2931, -0.9757,  0.7496,
          0.5320, -0.1149,  0.9058, -0.9204, -0.5359,  0.4025, -0.1804,  0.1258,
          0.5111,  0.5503, -0.2998,  0.0432, -0.2606, -0.2305, -0.9794,  0.2357,
          1.0000, -0.1366,  0.2072, -0.3135, -0.0742, -0.2608,  0.4649,  0.5246,
         -0.3008, -0.8875,  0.4085, -0.9680, -0.9851,  0.8283,  0.1803, -0.2321,
          1.0000,  0.3554,  0.1937, -0.0985,  0.9172, -0.0473,  0.5965,  0.4437,
          0.9816, -0.2481,  0.4739,  0.9016, -0.5753, -0.3746, -0.6518, -0.0358,
         -0.9181,  0.0855, -0.9622,  0.9680,  0.4307,  0.3884,  0.1690,  0.2911,
          1.0000, -0.1712,  0.5977, -0.6030,  0.8935, -0.9893, -0.8622, -0.3120,
          0.0271, -0.3242, -0.3122,  0.2444, -0.9702,  0.4015,  0.2745, -0.9923,
         -0.9909,  0.2219,  0.8963,  0.0339, -0.8774, -0.7099, -0.6496,  0.5307,
         -0.2593, -0.9483,  0.1670, -0.2551,  0.5264, -0.2670,  0.5001,  0.2517,
          0.7679,  0.0960, -0.0358,  0.0134, -0.7809,  0.8462, -0.8777, -0.6857,
         -0.1027,  1.0000, -0.4233,  0.5930,  0.8444,  0.7841, -0.1195,  0.2111,
          0.6052,  0.1554, -0.1903, -0.3731, -0.8628, -0.4653,  0.6401, -0.0441,
          0.2139,  0.7868,  0.5002,  0.1493,  0.0508,  0.0042,  0.9998, -0.1991,
         -0.1160, -0.5280, -0.0688, -0.2809, -0.5314,  1.0000,  0.3705,  0.3965,
         -0.9901, -0.4718, -0.9447,  1.0000,  0.8314, -0.8313,  0.5775,  0.4040,
         -0.0683,  0.8545, -0.1830, -0.2794,  0.2240,  0.1262,  0.9669, -0.4513,
         -0.9668, -0.5882,  0.4307, -0.9694,  0.9960, -0.5044, -0.2745, -0.2873,
         -0.0300,  0.8000,  0.0120, -0.9837, -0.2284,  0.0713,  0.9708,  0.1875,
         -0.5173, -0.9443,  0.1124,  0.3328, -0.5024, -0.9344,  0.9745, -0.9851,
          0.6481,  1.0000,  0.2872, -0.3557,  0.1554, -0.5277,  0.2990, -0.0038,
          0.6788, -0.9592, -0.3009, -0.1790,  0.2525, -0.1998,  0.2353,  0.7735,
          0.2068, -0.4473, -0.5484, -0.1180,  0.4598,  0.8757, -0.2999, -0.1064,
          0.0758, -0.1337, -0.9463, -0.2969, -0.3185, -0.9994,  0.6110, -1.0000,
         -0.0856, -0.1484, -0.2471,  0.8600,  0.1967,  0.3270, -0.8057, -0.4758,
          0.7115,  0.8006, -0.2512, -0.2940, -0.8110,  0.2632, -0.1152,  0.3325,
         -0.2631,  0.7758, -0.1797,  1.0000,  0.0619, -0.6463, -0.9863,  0.2094,
         -0.1875,  1.0000, -0.9405, -0.9439,  0.4023, -0.6165, -0.8564,  0.2523,
         -0.0753, -0.6538, -0.7368,  0.9703,  0.9149, -0.5242,  0.5691, -0.3519,
         -0.5723,  0.0547,  0.3502,  0.9856,  0.3457,  0.9356,  0.5885, -0.1173,
          0.9695,  0.1759,  0.7628,  0.1299,  1.0000,  0.3276, -0.9180,  0.3441,
         -0.9880, -0.1348, -0.9622,  0.3187,  0.1787,  0.9135, -0.2862,  0.9708,
         -0.4045,  0.1406, -0.2826,  0.1525,  0.3806, -0.9355, -0.9807, -0.9852,
          0.5491, -0.4982, -0.0202,  0.1725,  0.1148,  0.3453,  0.4091, -1.0000,
          0.9399,  0.4443,  0.4424,  0.9673,  0.4668,  0.4163,  0.2049, -0.9870,
         -0.9870, -0.3445, -0.2498,  0.8362,  0.6976,  0.8951,  0.4442, -0.5115,
         -0.2194, -0.1145, -0.2362, -0.9929,  0.3998, -0.2338, -0.9778,  0.9569,
         -0.4545, -0.1854,  0.3251, -0.4279,  0.9719,  0.8003,  0.4459,  0.1713,
          0.4570,  0.9070,  0.9659,  0.9861, -0.4308,  0.8346, -0.2344,  0.5230,
          0.3839, -0.9336,  0.0346,  0.2982, -0.2457,  0.2038, -0.2255, -0.9797,
          0.6798, -0.0993,  0.5073, -0.4992,  0.1172, -0.4750, -0.2779, -0.7481,
         -0.6828,  0.5748,  0.3778,  0.9186,  0.5620, -0.0173, -0.7420, -0.1573,
         -0.2497, -0.9132,  0.9582, -0.1153,  0.1211,  0.2608, -0.0592,  0.7554,
          0.0138, -0.4165, -0.2913, -0.7337,  0.9061, -0.3213, -0.5446, -0.6428,
          0.7181,  0.3104,  0.9993, -0.3464, -0.6236, -0.3280, -0.3728,  0.2671,
         -0.3797, -1.0000,  0.4521, -0.1108,  0.4458, -0.3040,  0.1689, -0.3587,
         -0.9865, -0.2440,  0.1362,  0.2268, -0.5546, -0.5949,  0.5401, -0.1452,
          0.8638,  0.9060, -0.1008,  0.4754,  0.5926, -0.1426, -0.7055,  0.9103]],
       grad_fn=<TanhBackward0>), hidden_states=None, past_key_values=None, attentions=None, cross_attentions=None)